/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IStandardCreativeNFT,
  IStandardCreativeNFTInterface,
} from "../IStandardCreativeNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IStandardCreativeNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IStandardCreativeNFTInterface {
    return new utils.Interface(_abi) as IStandardCreativeNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IStandardCreativeNFT {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IStandardCreativeNFT;
  }
}
