aws/
awscliv2.zip
.git/
*docker-compose*
node_modules
kubectl
lib/
packages/client/dist
packages/native-plugin-example
packages/docs
packages/ops
readme/
tests/
vendor/
packages/**/node_modules
package-lock.json
packages/**/package-lock.json
packages/analytics
packages/bot
packages/client
packages/client-core
packages/editor
packages/gameserver
packages/ops
packages/test


kubernetes/**
.vscode
config/prod.json

.env
.env.local
.idea/
