ARG REPO_URL
ARG REPO_NAME
ARG STAGE
ARG TAG
FROM ${REPO_URL}/${REPO_NAME}-root:${TAG} as builder

# Create app directory
WORKDIR /app

COPY project-package-jsons ./
COPY packages/server/package.json ./packages/server/

ARG NODE_ENV
RUN npm install --loglevel notice --legacy-peer-deps --production

COPY . .

# copy then compile the code

ENV APP_ENV=production

FROM node:22-slim as runner
RUN apt update
RUN apt-get -y install git
RUN apt-get -y install git-lfs
WORKDIR /app

COPY --from=builder /app ./

RUN bash ./scripts/setup_helm.sh

CMD ["scripts/start-server.sh"]
