export const DefaultBlendspaceValues = {
  MOVEMENT_IDLE: 0,
  MOVEMENT_WALKING_FORWARD: 1,
  MOVEMENT_JOGGING_FORWARD: 2,
  MOVEMENT_RUNNING_FORWARD: 3,
  MOVEMENT_WALKING_BACKWARD: 4,
  MOVEMENT_JOGGING_BACKWARD: 5,
  MOVEMENT_STRAFING_RIGHT: 6,
  MOVEMENT_STRAFING_LEFT: 7,
  MOVEMENT_RUNNING_BACKWARD: 8
}

export default DefaultBlendspaceValues
