# not slim because we need github depedencies
FROM node:16-buster

RUN apt update
# Create app directory
WORKDIR /app

RUN npm run build-docker

ENV APP_ENV=production

CMD ["scripts/start-server.sh"]
