# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster

RUN apt update
# Create app directory
WORKDIR /app

COPY package.json .
COPY packages/analytics/package.json ./packages/analytics/
COPY packages/client/package.json ./packages/client/
COPY packages/client-core/package.json ./packages/client-core/
COPY packages/common/package.json ./packages/common/
COPY packages/editor/package.json ./packages/editor/
COPY packages/engine/package.json ./packages/engine/
COPY packages/gameserver/package.json ./packages/gameserver/
COPY packages/matchmaking/package.json ./packages/matchmaking/
COPY packages/server/package.json ./packages/server/
COPY packages/server-core/package.json ./packages/server-core/
COPY packages/projects/package.json ./packages/projects/
COPY project-package-jsons ./

RUN npm install --production=false --loglevel notice --legacy-peer-deps

# copy then compile the code
COPY . .

RUN npm run build-client

ENV APP_ENV=production

CMD ["scripts/start-server.sh"]
