"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const upload_service_1 = __importDefault(require("./upload/upload.service"));
const email_service_1 = __importDefault(require("./email/email.service"));
const auth_management_service_1 = __importDefault(require("./auth-management/auth-management.service"));
const user_service_1 = __importDefault(require("./user/user.service"));
const group_service_1 = __importDefault(require("./group/group.service"));
const contact_service_1 = __importDefault(require("./contact/contact.service"));
const scene_object_service_1 = __importDefault(require("./scene-object/scene-object.service"));
const avatar_service_1 = __importDefault(require("./avatar/avatar.service"));
const object_service_1 = __importDefault(require("./object/object.service"));
const scene_service_1 = __importDefault(require("./scene/scene.service"));
const location_service_1 = __importDefault(require("./location/location.service"));
const instance_service_1 = __importDefault(require("./instance/instance.service"));
const public_video_service_1 = __importDefault(require("./public-video/public-video.service"));
exports.default = (app) => {
    app.configure(upload_service_1.default);
    app.configure(email_service_1.default);
    app.configure(auth_management_service_1.default);
    app.configure(user_service_1.default);
    app.configure(group_service_1.default);
    app.configure(contact_service_1.default);
    app.configure(scene_object_service_1.default);
    app.configure(avatar_service_1.default);
    app.configure(object_service_1.default);
    app.configure(scene_service_1.default);
    app.configure(location_service_1.default);
    app.configure(instance_service_1.default);
    app.configure(public_video_service_1.default);
};
