// Auth Actions
export const LOGIN_PROCESSING = 'LOGIN_PROCESSING';
export const LOGIN_USER_BY_EMAIL_SUCCESS = 'LOGIN_USER_BY_EMAIL_SUCCESS';
export const LOGIN_USER_BY_EMAIL_ERROR = 'LOGIN_USER_BY_EMAIL_ERROR';

export const LOGIN_USER_BY_GITHUB_SUCCESS = 'LOGIN_USER_BY_GITHUB_SUCCESS';
export const LOGIN_USER_BY_GITHUB_ERROR = 'LOGIN_USER_BY_GITHUB_ERROR';

export const LOGIN_USER_BY_FACEBOOK_SUCCESS = 'LOGIN_USER_BY_FACEBOOK_SUCCESS';
export const LOGIN_USER_BY_FACEBOOK_ERROR = 'LOGIN_USER_BY_FACEBOOK_ERROR';

export const LOGIN_USER_BY_GOOGLE_SUCCESS = 'LOGIN_USER_BY_GOOGLE_SUCCESS';
export const LOGIN_USER_BY_GOOGLE_ERROR = 'LOGIN_USER_BY_GOOGLE_ERROR';

export const REGISTER_PROCESSING = 'REGISTER_PROCESSING';
export const REGISTER_USER_BY_EMAIL_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_BY_EMAIL_ERROR = 'REGISTER_USER_ERROR';

export const LOGOUT_PROCESSING = 'LOGOUT_PROCESSING';
export const LOGOUT_USER = 'LOGOUT_USER';
