# Use the official Node.js image as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Install dependencies for Chrome
RUN apt-get update && apt-get install -y wget gnupg

# Add Chrome to the apt repository
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list

# Install Chrome
RUN apt-get update && apt-get install -y google-chrome-stable

# Clone the repository and install dependencies
RUN git clone https://github.com/SYBIOTE/ee-bot .
RUN npm install
 
# Set the command to run when the container starts
CMD ["npm", "run", "dev"]

# Set a healthcheck for the container
HEALTHCHECK --interval=10s --timeout=2s --retries=3 \
    CMD curl --fail http://localhost:4000/ || exit 1

# we check if the bot API is up and running or not
