export const SET_APP_LOADED = 'SET_APP_LOADED'

export const LOADED_SEATS = 'LOADED_SEATS'
export const INVITED_USER = 'INVITED_USER'
export const CANCELED_INVITATION = 'CANCELED_INVITATION'
export const REMOVED_SEAT = 'REMOVED_SEAT'

export const SET_APP_LOADING_PERCENT = 'SET_APP_LOADING_PERCENT'

export const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE'

export const SET_IN_VR_MODE = 'SET_IN_VR_MODE'

export const SET_USER_HAS_INTERACTED = 'SET_USER_HAS_INTERACTED'

export const SET_APP_ONBOARDING_STEP = 'SET_APP_ONBOARDING_STEP'
export const SET_APP_SPECIFIC_ONBOARDING_STEP = 'SET_APP_SPECIFIC_ONBOARDING_STEP'

export const SHOW_DIALOG = 'SHOW_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'
export const SET_SCOPE_READ_ERROR = 'SET_SCOPE_READ_ERROR'
export const SET_SCOPE_WRITE_ERROR = 'SET_SCOPE_WRITE_ERROR'
