export const SET_APP_LOADED = 'SET_APP_LOADED';

export const LOADED_RELATIONSHIP = 'LOADED_RELATIONSHIP';
// export const LOADED_USERS = 'LOADED_USERS';
export const CHANGED_RELATION = 'CHANGED_RELATION';
export const CLEAR_LAYER_USERS = 'CLEAR_LAYER_USERS';
export const LOADED_LAYER_USERS = 'LOADED_LAYER_USERS';
export const ADDED_LAYER_USER = 'ADDED_LAYER_USER';
export const REMOVED_LAYER_USER = 'REMOVED_LAYER_USER';
export const USER_TOAST = 'USER_TOAST';

export const LOADED_SEATS = 'LOADED_SEATS';
export const INVITED_USER = 'INVITED_USER';
export const CANCELED_INVITATION = 'CANCELED_INVITATION';
export const REMOVED_SEAT = 'REMOVED_SEAT';

export const SET_APP_LOADING_PERCENT = 'SET_APP_LOADING_PERCENT';

export const SET_VIEWPORT_SIZE = 'SET_VIEWPORT_SIZE';

export const SET_IN_VR_MODE = 'SET_IN_VR_MODE';

export const SET_USER_HAS_INTERACTED = 'SET_USER_HAS_INTERACTED';

export const SET_APP_ONBOARDING_STEP = 'SET_APP_ONBOARDING_STEP';
export const SET_APP_SPECIFIC_ONBOARDING_STEP = 'SET_APP_SPECIFIC_ONBOARDING_STEP';

export const SHOW_DIALOG = 'SHOW_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';