ARG ECR_URL
ARG REPO_NAME
ARG STAGE
FROM $ECR_URL/$REPO_NAME-root:latest_${STAGE} as builder

COPY . .

CMD ["scripts/strip-engine.sh"]

# copy then compile the code

ENV APP_ENV=production

FROM node:18-buster-slim as runner
WORKDIR /app

# This commands runs the setup_helm.sh script to install helm and relevent installations
COPY ../../scripts/setup_helm.sh .
RUN chmod +x setup_helm.sh && ./setup_helm.sh


COPY --from=builder /app ./

CMD ["scripts/run-builder.sh"]
