aws/
awscliv2.zip
.git/
*docker-compose*
node_modules
kubectl
lib/
packages/client/dist
packages/native-plugin-example
packages/ops
readme/
vendor/
packages/**/node_modules
package-lock.json
packages/**/package-lock.json
packages/ops
packages/test

kubernetes/**
.vscode
config/prod.json

.env
.env.local
.idea/
