
    //
// THIS FILE WAS GENERATED BY `react-native-wasm`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

    #pragma once
    #include "jsi-imports-bridge.h"

    namespace facebook::react {

    jsi::Object createRapier__wasm3d__bgExports(jsi::Runtime &rt, jsi::Object&& importObject);

    }
