//
// THIS FILE WAS GENERATED BY `react-native-wasm`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#pragma once
#include <jsi/jsi.h>
#include <ReactNativePolygen/gen-utils.h>
#include "rapier_wasm3d_bg.h"

GEN_IMPORT_CONTEXT_TYPE(w2c_wbg, w2c_rapier__wasm3d__bg);

namespace facebook::react {

class Rapier__wasm3d__bgModuleContext: public jsi::NativeState {
public:
  Rapier__wasm3d__bgModuleContext(jsi::Runtime& rt, jsi::Object&& importObject)
    : importObject(std::move(importObject))
    , INIT_IMPORT_CTX(import_wbgCtx, "wbg")
  {}

  jsi::Object importObject;
  w2c_rapier__wasm3d__bg rootCtx;
  w2c_wbg import_wbgCtx;
};
}
