//
// THIS FILE WAS GENERATED BY `polygen`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#pragma once
#include "rapier_wasm3d_bg.h"
#include "wbg-imports.h"

namespace callstack::polygen::generated {

class Rapier__wasm3d__bgModuleContext: public facebook::jsi::NativeState {
public:
  Rapier__wasm3d__bgModuleContext(facebook::jsi::Runtime& rt, facebook::jsi::Object&& importObject)
    : importObject(std::move(importObject))
    , INIT_IMPORT_CTX(import_wbgCtx, "wbg")
  {}

  facebook::jsi::Object importObject;
  w2c_rapier__wasm3d__bg rootCtx;
  w2c_wbg import_wbgCtx;
};

void createRapier__wasm3d__bgExports(facebook::jsi::Runtime &rt, facebook::jsi::Object& target, facebook::jsi::Object&& importObject);

}
