/* Automatically generated by wasm2c */
#ifndef RAPIER_WASM3D_BG_H_GENERATED_
#define RAPIER_WASM3D_BG_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wbg;

typedef struct w2c_rapier__wasm3d__bg {
  struct w2c_wbg* w2c_wbg_instance;
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_T0;
} w2c_rapier__wasm3d__bg;

void wasm2c_rapier__wasm3d__bg_instantiate(w2c_rapier__wasm3d__bg*, struct w2c_wbg*);
void wasm2c_rapier__wasm3d__bg_free(w2c_rapier__wasm3d__bg*);
wasm_rt_func_type_t wasm2c_rapier__wasm3d__bg_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wbg' '__wbg_bind_10dfe70e95d2a480' */
u32 w2c_wbg_0x5F_wbg_bind_10dfe70e95d2a480(struct w2c_wbg*, u32, u32, u32, u32);

/* import: 'wbg' '__wbg_buffer_3f3d764d4747d564' */
u32 w2c_wbg_0x5F_wbg_buffer_3f3d764d4747d564(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_call_168da88779e35f61' */
u32 w2c_wbg_0x5F_wbg_call_168da88779e35f61(struct w2c_wbg*, u32, u32, u32);

/* import: 'wbg' '__wbg_call_3999bee59e9f7719' */
u32 w2c_wbg_0x5F_wbg_call_3999bee59e9f7719(struct w2c_wbg*, u32, u32, u32, u32);

/* import: 'wbg' '__wbg_call_e1f72c051cdab859' */
u32 w2c_wbg_0x5F_wbg_call_e1f72c051cdab859(struct w2c_wbg*, u32, u32, u32, u32, u32);

/* import: 'wbg' '__wbg_length_9a2deed95d22668d' */
u32 w2c_wbg_0x5F_wbg_length_9a2deed95d22668d(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_length_9e1ae1900cb0fbd5' */
u32 w2c_wbg_0x5F_wbg_length_9e1ae1900cb0fbd5(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_new_8c3f0052272a457a' */
u32 w2c_wbg_0x5F_wbg_new_8c3f0052272a457a(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_newwithbyteoffsetandlength_be22e5fcf4f69ab4' */
u32 w2c_wbg_0x5F_wbg_newwithbyteoffsetandlength_be22e5fcf4f69ab4(struct w2c_wbg*, u32, u32, u32);

/* import: 'wbg' '__wbg_newwithbyteoffsetandlength_d9aa266703cb98be' */
u32 w2c_wbg_0x5F_wbg_newwithbyteoffsetandlength_d9aa266703cb98be(struct w2c_wbg*, u32, u32, u32);

/* import: 'wbg' '__wbg_newwithlength_a7168e4a1e8f5e12' */
u32 w2c_wbg_0x5F_wbg_newwithlength_a7168e4a1e8f5e12(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_rawcontactforceevent_new' */
u32 w2c_wbg_0x5F_wbg_rawcontactforceevent_new(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_rawraycolliderintersection_new' */
u32 w2c_wbg_0x5F_wbg_rawraycolliderintersection_new(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbg_set_0e0314cf6675c1b9' */
void w2c_wbg_0x5F_wbg_set_0e0314cf6675c1b9(struct w2c_wbg*, u32, u32, u32);

/* import: 'wbg' '__wbg_set_83db9690f9353e79' */
void w2c_wbg_0x5F_wbg_set_83db9690f9353e79(struct w2c_wbg*, u32, u32, u32);

/* import: 'wbg' '__wbindgen_boolean_get' */
u32 w2c_wbg_0x5F_wbindgen_boolean_get(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbindgen_is_function' */
u32 w2c_wbg_0x5F_wbindgen_is_function(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbindgen_memory' */
u32 w2c_wbg_0x5F_wbindgen_memory(struct w2c_wbg*);

/* import: 'wbg' '__wbindgen_number_get' */
void w2c_wbg_0x5F_wbindgen_number_get(struct w2c_wbg*, u32, u32);

/* import: 'wbg' '__wbindgen_number_new' */
u32 w2c_wbg_0x5F_wbindgen_number_new(struct w2c_wbg*, f64);

/* import: 'wbg' '__wbindgen_object_drop_ref' */
void w2c_wbg_0x5F_wbindgen_object_drop_ref(struct w2c_wbg*, u32);

/* import: 'wbg' '__wbindgen_throw' */
void w2c_wbg_0x5F_wbindgen_throw(struct w2c_wbg*, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_rapier__wasm3d__bg_memory(w2c_rapier__wasm3d__bg* instance);

/* export: 'version' */
void w2c_rapier__wasm3d__bg_version(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawkinematiccharactercontroller_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawkinematiccharactercontroller_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_new' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_new(w2c_rapier__wasm3d__bg*, f32);

/* export: 'rawkinematiccharactercontroller_up' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_up(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_setUp' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_setUp(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawkinematiccharactercontroller_offset' */
f32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_offset(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_setOffset' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_setOffset(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawkinematiccharactercontroller_slideEnabled' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_slideEnabled(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_setSlideEnabled' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_setSlideEnabled(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawkinematiccharactercontroller_autostepMaxHeight' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_autostepMaxHeight(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawkinematiccharactercontroller_autostepMinWidth' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_autostepMinWidth(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawkinematiccharactercontroller_autostepIncludesDynamicBodies' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_autostepIncludesDynamicBodies(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_autostepEnabled' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_autostepEnabled(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_enableAutostep' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_enableAutostep(w2c_rapier__wasm3d__bg*, u32, f32, f32, u32);

/* export: 'rawkinematiccharactercontroller_disableAutostep' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_disableAutostep(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_maxSlopeClimbAngle' */
f32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_maxSlopeClimbAngle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_setMaxSlopeClimbAngle' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_setMaxSlopeClimbAngle(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawkinematiccharactercontroller_minSlopeSlideAngle' */
f32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_minSlopeSlideAngle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_setMinSlopeSlideAngle' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_setMinSlopeSlideAngle(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawkinematiccharactercontroller_snapToGroundDistance' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_snapToGroundDistance(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawkinematiccharactercontroller_enableSnapToGround' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_enableSnapToGround(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawkinematiccharactercontroller_disableSnapToGround' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_disableSnapToGround(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_snapToGroundEnabled' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_snapToGroundEnabled(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_computeColliderMovement' */
void w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_computeColliderMovement(w2c_rapier__wasm3d__bg*, u32, f32, u32, u32, u32, f64, u32, u32, u32, f32, u32, u32, u32, u32);

/* export: 'rawkinematiccharactercontroller_computedMovement' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_computedMovement(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_computedGrounded' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_computedGrounded(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_numComputedCollisions' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_numComputedCollisions(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawkinematiccharactercontroller_computedCollision' */
u32 w2c_rapier__wasm3d__bg_rawkinematiccharactercontroller_computedCollision(w2c_rapier__wasm3d__bg*, u32, u32, u32);

/* export: '__wbg_rawcharactercollision_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawcharactercollision_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_new' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawcharactercollision_handle' */
f64 w2c_rapier__wasm3d__bg_rawcharactercollision_handle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_translationApplied' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_translationApplied(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_translationRemaining' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_translationRemaining(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_toi' */
f32 w2c_rapier__wasm3d__bg_rawcharactercollision_toi(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_worldWitness1' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_worldWitness1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_worldWitness2' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_worldWitness2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_worldNormal1' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_worldNormal1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcharactercollision_worldNormal2' */
u32 w2c_rapier__wasm3d__bg_rawcharactercollision_worldNormal2(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawccdsolver_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawccdsolver_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawccdsolver_new' */
u32 w2c_rapier__wasm3d__bg_rawccdsolver_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawimpulsejointset_jointType' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointType(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointBodyHandle1' */
f64 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointBodyHandle1(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointBodyHandle2' */
f64 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointBodyHandle2(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointFrameX1' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointFrameX1(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointFrameX2' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointFrameX2(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointAnchor1' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointAnchor1(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointAnchor2' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointAnchor2(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointSetAnchor1' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointSetAnchor1(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_jointSetAnchor2' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointSetAnchor2(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_jointContactsEnabled' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointContactsEnabled(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_jointSetContactsEnabled' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointSetContactsEnabled(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_jointLimitsEnabled' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointLimitsEnabled(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_jointLimitsMin' */
f32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointLimitsMin(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_jointLimitsMax' */
f32 w2c_rapier__wasm3d__bg_rawimpulsejointset_jointLimitsMax(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_jointSetLimits' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointSetLimits(w2c_rapier__wasm3d__bg*, u32, f64, u32, f32, f32);

/* export: 'rawimpulsejointset_jointConfigureMotorModel' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointConfigureMotorModel(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawimpulsejointset_jointConfigureMotorVelocity' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointConfigureMotorVelocity(w2c_rapier__wasm3d__bg*, u32, f64, u32, f32, f32);

/* export: 'rawimpulsejointset_jointConfigureMotorPosition' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointConfigureMotorPosition(w2c_rapier__wasm3d__bg*, u32, f64, u32, f32, f32, f32);

/* export: 'rawimpulsejointset_jointConfigureMotor' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_jointConfigureMotor(w2c_rapier__wasm3d__bg*, u32, f64, u32, f32, f32, f32, f32);

/* export: '__wbg_rawimpulsejointset_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawimpulsejointset_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawimpulsejointset_new' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawimpulsejointset_createJoint' */
f64 w2c_rapier__wasm3d__bg_rawimpulsejointset_createJoint(w2c_rapier__wasm3d__bg*, u32, u32, f64, f64, u32);

/* export: 'rawimpulsejointset_remove' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_remove(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawimpulsejointset_len' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_len(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawimpulsejointset_contains' */
u32 w2c_rapier__wasm3d__bg_rawimpulsejointset_contains(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawimpulsejointset_forEachJointHandle' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_forEachJointHandle(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawimpulsejointset_forEachJointAttachedToRigidBody' */
void w2c_rapier__wasm3d__bg_rawimpulsejointset_forEachJointAttachedToRigidBody(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: '__wbg_rawintegrationparameters_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawintegrationparameters_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_new' */
u32 w2c_rapier__wasm3d__bg_rawintegrationparameters_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawintegrationparameters_dt' */
f32 w2c_rapier__wasm3d__bg_rawintegrationparameters_dt(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_allowedLinearError' */
f32 w2c_rapier__wasm3d__bg_rawintegrationparameters_allowedLinearError(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_predictionDistance' */
f32 w2c_rapier__wasm3d__bg_rawintegrationparameters_predictionDistance(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_maxVelocityIterations' */
u32 w2c_rapier__wasm3d__bg_rawintegrationparameters_maxVelocityIterations(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_maxVelocityFrictionIterations' */
u32 w2c_rapier__wasm3d__bg_rawintegrationparameters_maxVelocityFrictionIterations(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_maxStabilizationIterations' */
u32 w2c_rapier__wasm3d__bg_rawintegrationparameters_maxStabilizationIterations(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_minIslandSize' */
u32 w2c_rapier__wasm3d__bg_rawintegrationparameters_minIslandSize(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_maxCcdSubsteps' */
u32 w2c_rapier__wasm3d__bg_rawintegrationparameters_maxCcdSubsteps(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawintegrationparameters_set_dt' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_dt(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawintegrationparameters_set_erp' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_erp(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawintegrationparameters_set_allowedLinearError' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_allowedLinearError(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawintegrationparameters_set_predictionDistance' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_predictionDistance(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawintegrationparameters_set_maxVelocityIterations' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_maxVelocityIterations(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawintegrationparameters_set_maxVelocityFrictionIterations' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_maxVelocityFrictionIterations(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawintegrationparameters_set_maxStabilizationIterations' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_maxStabilizationIterations(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawintegrationparameters_set_minIslandSize' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_minIslandSize(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawintegrationparameters_set_maxCcdSubsteps' */
void w2c_rapier__wasm3d__bg_rawintegrationparameters_set_maxCcdSubsteps(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawislandmanager_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawislandmanager_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawislandmanager_new' */
u32 w2c_rapier__wasm3d__bg_rawislandmanager_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawislandmanager_forEachActiveRigidBodyHandle' */
void w2c_rapier__wasm3d__bg_rawislandmanager_forEachActiveRigidBodyHandle(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawgenericjoint_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawgenericjoint_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawgenericjoint_spherical' */
u32 w2c_rapier__wasm3d__bg_rawgenericjoint_spherical(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawgenericjoint_prismatic' */
u32 w2c_rapier__wasm3d__bg_rawgenericjoint_prismatic(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, f32, f32);

/* export: 'rawgenericjoint_fixed' */
u32 w2c_rapier__wasm3d__bg_rawgenericjoint_fixed(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32);

/* export: 'rawgenericjoint_revolute' */
u32 w2c_rapier__wasm3d__bg_rawgenericjoint_revolute(w2c_rapier__wasm3d__bg*, u32, u32, u32);

/* export: 'rawmultibodyjointset_jointType' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointType(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_jointFrameX1' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointFrameX1(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_jointFrameX2' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointFrameX2(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_jointAnchor1' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointAnchor1(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_jointAnchor2' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointAnchor2(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_jointContactsEnabled' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointContactsEnabled(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_jointSetContactsEnabled' */
void w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointSetContactsEnabled(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawmultibodyjointset_jointLimitsEnabled' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointLimitsEnabled(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawmultibodyjointset_jointLimitsMin' */
f32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointLimitsMin(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawmultibodyjointset_jointLimitsMax' */
f32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_jointLimitsMax(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: '__wbg_rawmultibodyjointset_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawmultibodyjointset_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawmultibodyjointset_new' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawmultibodyjointset_createJoint' */
f64 w2c_rapier__wasm3d__bg_rawmultibodyjointset_createJoint(w2c_rapier__wasm3d__bg*, u32, u32, f64, f64, u32);

/* export: 'rawmultibodyjointset_remove' */
void w2c_rapier__wasm3d__bg_rawmultibodyjointset_remove(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawmultibodyjointset_contains' */
u32 w2c_rapier__wasm3d__bg_rawmultibodyjointset_contains(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawmultibodyjointset_forEachJointHandle' */
void w2c_rapier__wasm3d__bg_rawmultibodyjointset_forEachJointHandle(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawmultibodyjointset_forEachJointAttachedToRigidBody' */
void w2c_rapier__wasm3d__bg_rawmultibodyjointset_forEachJointAttachedToRigidBody(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbTranslation' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbTranslation(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbRotation' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbRotation(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSleep' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSleep(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbIsSleeping' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsSleeping(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbIsMoving' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsMoving(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbNextTranslation' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbNextTranslation(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbNextRotation' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbNextRotation(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSetTranslation' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetTranslation(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32, u32);

/* export: 'rawrigidbodyset_rbSetRotation' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetRotation(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32, f32, u32);

/* export: 'rawrigidbodyset_rbSetLinvel' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetLinvel(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbSetAngvel' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetAngvel(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbSetNextKinematicTranslation' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetNextKinematicTranslation(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32);

/* export: 'rawrigidbodyset_rbSetNextKinematicRotation' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetNextKinematicRotation(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32, f32);

/* export: 'rawrigidbodyset_rbRecomputeMassPropertiesFromColliders' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbRecomputeMassPropertiesFromColliders(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbSetAdditionalMass' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetAdditionalMass(w2c_rapier__wasm3d__bg*, u32, f64, f32, u32);

/* export: 'rawrigidbodyset_rbSetAdditionalMassProperties' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetAdditionalMassProperties(w2c_rapier__wasm3d__bg*, u32, f64, f32, u32, u32, u32, u32);

/* export: 'rawrigidbodyset_rbLinvel' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbLinvel(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbAngvel' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbAngvel(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbLockTranslations' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbLockTranslations(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbSetEnabledTranslations' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetEnabledTranslations(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32, u32);

/* export: 'rawrigidbodyset_rbLockRotations' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbLockRotations(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbSetEnabledRotations' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetEnabledRotations(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32, u32);

/* export: 'rawrigidbodyset_rbDominanceGroup' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbDominanceGroup(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSetDominanceGroup' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetDominanceGroup(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbEnableCcd' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbEnableCcd(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbMass' */
f32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbMass(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbInvMass' */
f32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbInvMass(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbEffectiveInvMass' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbEffectiveInvMass(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbLocalCom' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbLocalCom(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbWorldCom' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbWorldCom(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbInvPrincipalInertiaSqrt' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbInvPrincipalInertiaSqrt(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbPrincipalInertiaLocalFrame' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbPrincipalInertiaLocalFrame(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbPrincipalInertia' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbPrincipalInertia(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbEffectiveWorldInvInertiaSqrt' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbEffectiveWorldInvInertiaSqrt(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbEffectiveAngularInertia' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbEffectiveAngularInertia(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbWakeUp' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbWakeUp(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbIsCcdEnabled' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsCcdEnabled(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbNumColliders' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbNumColliders(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbCollider' */
f64 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbCollider(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbBodyType' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbBodyType(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSetBodyType' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetBodyType(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbIsFixed' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsFixed(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbIsKinematic' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsKinematic(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbIsDynamic' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsDynamic(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbLinearDamping' */
f32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbLinearDamping(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbAngularDamping' */
f32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbAngularDamping(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSetLinearDamping' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetLinearDamping(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawrigidbodyset_rbSetAngularDamping' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetAngularDamping(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawrigidbodyset_rbSetEnabled' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetEnabled(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbIsEnabled' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbIsEnabled(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbGravityScale' */
f32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbGravityScale(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSetGravityScale' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetGravityScale(w2c_rapier__wasm3d__bg*, u32, f64, f32, u32);

/* export: 'rawrigidbodyset_rbResetForces' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbResetForces(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbResetTorques' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbResetTorques(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawrigidbodyset_rbAddForce' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbAddForce(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbApplyImpulse' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbApplyImpulse(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbAddTorque' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbAddTorque(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbApplyTorqueImpulse' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbApplyTorqueImpulse(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawrigidbodyset_rbAddForceAtPoint' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbAddForceAtPoint(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32);

/* export: 'rawrigidbodyset_rbApplyImpulseAtPoint' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbApplyImpulseAtPoint(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32);

/* export: 'rawrigidbodyset_rbUserData' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_rbUserData(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_rbSetUserData' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_rbSetUserData(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: '__wbg_rawrigidbodyset_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawrigidbodyset_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrigidbodyset_new' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawrigidbodyset_createRigidBody' */
f64 w2c_rapier__wasm3d__bg_rawrigidbodyset_createRigidBody(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, f32, f32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, f32, f32, u32, u32, u32, u32, u32);

/* export: 'rawrigidbodyset_remove' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_remove(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32, u32);

/* export: 'rawrigidbodyset_len' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_len(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrigidbodyset_contains' */
u32 w2c_rapier__wasm3d__bg_rawrigidbodyset_contains(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawrigidbodyset_forEachRigidBodyHandle' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_forEachRigidBodyHandle(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawrigidbodyset_propagateModifiedBodyPositionsToColliders' */
void w2c_rapier__wasm3d__bg_rawrigidbodyset_propagateModifiedBodyPositionsToColliders(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawbroadphase_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawbroadphase_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawbroadphase_new' */
u32 w2c_rapier__wasm3d__bg_rawbroadphase_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawcolliderset_coTranslation' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coTranslation(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coRotation' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coRotation(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coSetTranslation' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetTranslation(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32);

/* export: 'rawcolliderset_coSetTranslationWrtParent' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetTranslationWrtParent(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32);

/* export: 'rawcolliderset_coSetRotation' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetRotation(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32, f32);

/* export: 'rawcolliderset_coSetRotationWrtParent' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetRotationWrtParent(w2c_rapier__wasm3d__bg*, u32, f64, f32, f32, f32, f32);

/* export: 'rawcolliderset_coIsSensor' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coIsSensor(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coShapeType' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coShapeType(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coHalfspaceNormal' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coHalfspaceNormal(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coHalfExtents' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coHalfExtents(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coSetHalfExtents' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetHalfExtents(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coRadius' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coRadius(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coSetRadius' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetRadius(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coHalfHeight' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coHalfHeight(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coSetHalfHeight' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetHalfHeight(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coRoundRadius' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coRoundRadius(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coSetRoundRadius' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetRoundRadius(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coVertices' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coVertices(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coIndices' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coIndices(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coHeightfieldHeights' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coHeightfieldHeights(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coHeightfieldScale' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coHeightfieldScale(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coHeightfieldNRows' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coHeightfieldNRows(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coHeightfieldNCols' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coHeightfieldNCols(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coParent' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coParent(w2c_rapier__wasm3d__bg*, u32, u32, f64);

/* export: 'rawcolliderset_coSetEnabled' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetEnabled(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coIsEnabled' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coIsEnabled(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coFriction' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coFriction(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coRestitution' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coRestitution(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coDensity' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coDensity(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coMass' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coMass(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coVolume' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coVolume(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coCollisionGroups' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coCollisionGroups(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coSolverGroups' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coSolverGroups(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coActiveHooks' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coActiveHooks(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coActiveCollisionTypes' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coActiveCollisionTypes(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coActiveEvents' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coActiveEvents(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coContactForceEventThreshold' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coContactForceEventThreshold(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coContainsPoint' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coContainsPoint(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coCastShape' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coCastShape(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32, u32, u32, f32, u32);

/* export: 'rawcolliderset_coCastCollider' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coCastCollider(w2c_rapier__wasm3d__bg*, u32, f64, u32, f64, u32, f32, u32);

/* export: 'rawcolliderset_coIntersectsShape' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coIntersectsShape(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32);

/* export: 'rawcolliderset_coContactShape' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coContactShape(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32, f32);

/* export: 'rawcolliderset_coContactCollider' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coContactCollider(w2c_rapier__wasm3d__bg*, u32, f64, f64, f32);

/* export: 'rawcolliderset_coProjectPoint' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coProjectPoint(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32);

/* export: 'rawcolliderset_coIntersectsRay' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coIntersectsRay(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, f32);

/* export: 'rawcolliderset_coCastRay' */
f32 w2c_rapier__wasm3d__bg_rawcolliderset_coCastRay(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, f32, u32);

/* export: 'rawcolliderset_coCastRayAndGetNormal' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coCastRayAndGetNormal(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, f32, u32);

/* export: 'rawcolliderset_coSetSensor' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetSensor(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetRestitution' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetRestitution(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coSetFriction' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetFriction(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coFrictionCombineRule' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coFrictionCombineRule(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coSetFrictionCombineRule' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetFrictionCombineRule(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coRestitutionCombineRule' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_coRestitutionCombineRule(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_coSetRestitutionCombineRule' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetRestitutionCombineRule(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetCollisionGroups' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetCollisionGroups(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetSolverGroups' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetSolverGroups(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetActiveHooks' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetActiveHooks(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetActiveEvents' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetActiveEvents(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetActiveCollisionTypes' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetActiveCollisionTypes(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetShape' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetShape(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawcolliderset_coSetContactForceEventThreshold' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetContactForceEventThreshold(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coSetDensity' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetDensity(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coSetMass' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetMass(w2c_rapier__wasm3d__bg*, u32, f64, f32);

/* export: 'rawcolliderset_coSetMassProperties' */
void w2c_rapier__wasm3d__bg_rawcolliderset_coSetMassProperties(w2c_rapier__wasm3d__bg*, u32, f64, f32, u32, u32, u32);

/* export: '__wbg_rawcolliderset_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawcolliderset_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcolliderset_new' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawcolliderset_len' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_len(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcolliderset_contains' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_contains(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawcolliderset_createCollider' */
void w2c_rapier__wasm3d__bg_rawcolliderset_createCollider(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, f32, u32, u32, u32, f32, f32, f32, u32, u32, u32, u32, u32, u32, u32, u32, f32, u32, f64, u32);

/* export: 'rawcolliderset_remove' */
void w2c_rapier__wasm3d__bg_rawcolliderset_remove(w2c_rapier__wasm3d__bg*, u32, f64, u32, u32, u32);

/* export: 'rawcolliderset_forEachColliderHandle' */
void w2c_rapier__wasm3d__bg_rawcolliderset_forEachColliderHandle(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawshapecontact_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawshapecontact_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecontact_distance' */
f32 w2c_rapier__wasm3d__bg_rawshapecontact_distance(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawnarrowphase_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawnarrowphase_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawnarrowphase_new' */
u32 w2c_rapier__wasm3d__bg_rawnarrowphase_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawnarrowphase_contacts_with' */
void w2c_rapier__wasm3d__bg_rawnarrowphase_contacts_with(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawnarrowphase_contact_pair' */
u32 w2c_rapier__wasm3d__bg_rawnarrowphase_contact_pair(w2c_rapier__wasm3d__bg*, u32, f64, f64);

/* export: 'rawnarrowphase_intersections_with' */
void w2c_rapier__wasm3d__bg_rawnarrowphase_intersections_with(w2c_rapier__wasm3d__bg*, u32, f64, u32);

/* export: 'rawnarrowphase_intersection_pair' */
u32 w2c_rapier__wasm3d__bg_rawnarrowphase_intersection_pair(w2c_rapier__wasm3d__bg*, u32, f64, f64);

/* export: '__wbg_rawcontactmanifold_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawcontactmanifold_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactpair_collider1' */
f64 w2c_rapier__wasm3d__bg_rawcontactpair_collider1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactpair_collider2' */
f64 w2c_rapier__wasm3d__bg_rawcontactpair_collider2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactpair_numContactManifolds' */
u32 w2c_rapier__wasm3d__bg_rawcontactpair_numContactManifolds(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactpair_contactManifold' */
u32 w2c_rapier__wasm3d__bg_rawcontactpair_contactManifold(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_normal' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_normal(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_local_n1' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_local_n1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_local_n2' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_local_n2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_subshape1' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_subshape1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_subshape2' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_subshape2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_num_contacts' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_num_contacts(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_contact_local_p1' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_local_p1(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_local_p2' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_local_p2(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_dist' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_dist(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_fid1' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_fid1(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_fid2' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_fid2(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_impulse' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_impulse(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_tangent_impulse_x' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_tangent_impulse_x(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_contact_tangent_impulse_y' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_contact_tangent_impulse_y(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_num_solver_contacts' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_num_solver_contacts(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactmanifold_solver_contact_point' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_solver_contact_point(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_solver_contact_dist' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_solver_contact_dist(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_solver_contact_friction' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_solver_contact_friction(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_solver_contact_restitution' */
f32 w2c_rapier__wasm3d__bg_rawcontactmanifold_solver_contact_restitution(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawcontactmanifold_solver_contact_tangent_velocity' */
u32 w2c_rapier__wasm3d__bg_rawcontactmanifold_solver_contact_tangent_velocity(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawpointprojection_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawpointprojection_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawpointcolliderprojection_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawpointcolliderprojection_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawpointcolliderprojection_colliderHandle' */
f64 w2c_rapier__wasm3d__bg_rawpointcolliderprojection_colliderHandle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawpointcolliderprojection_featureType' */
u32 w2c_rapier__wasm3d__bg_rawpointcolliderprojection_featureType(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawpointcolliderprojection_featureId' */
void w2c_rapier__wasm3d__bg_rawpointcolliderprojection_featureId(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawrayintersection_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawrayintersection_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrayintersection_featureType' */
u32 w2c_rapier__wasm3d__bg_rawrayintersection_featureType(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrayintersection_featureId' */
void w2c_rapier__wasm3d__bg_rawrayintersection_featureId(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawraycolliderintersection_normal' */
u32 w2c_rapier__wasm3d__bg_rawraycolliderintersection_normal(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawraycolliderintersection_toi' */
f32 w2c_rapier__wasm3d__bg_rawraycolliderintersection_toi(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawraycolliderintersection_featureType' */
u32 w2c_rapier__wasm3d__bg_rawraycolliderintersection_featureType(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawraycolliderintersection_featureId' */
void w2c_rapier__wasm3d__bg_rawraycolliderintersection_featureId(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawraycollidertoi_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawraycollidertoi_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawshape_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawshape_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshape_cuboid' */
u32 w2c_rapier__wasm3d__bg_rawshape_cuboid(w2c_rapier__wasm3d__bg*, f32, f32, f32);

/* export: 'rawshape_roundCuboid' */
u32 w2c_rapier__wasm3d__bg_rawshape_roundCuboid(w2c_rapier__wasm3d__bg*, f32, f32, f32, f32);

/* export: 'rawshape_ball' */
u32 w2c_rapier__wasm3d__bg_rawshape_ball(w2c_rapier__wasm3d__bg*, f32);

/* export: 'rawshape_halfspace' */
u32 w2c_rapier__wasm3d__bg_rawshape_halfspace(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshape_capsule' */
u32 w2c_rapier__wasm3d__bg_rawshape_capsule(w2c_rapier__wasm3d__bg*, f32, f32);

/* export: 'rawshape_cylinder' */
u32 w2c_rapier__wasm3d__bg_rawshape_cylinder(w2c_rapier__wasm3d__bg*, f32, f32);

/* export: 'rawshape_roundCylinder' */
u32 w2c_rapier__wasm3d__bg_rawshape_roundCylinder(w2c_rapier__wasm3d__bg*, f32, f32, f32);

/* export: 'rawshape_cone' */
u32 w2c_rapier__wasm3d__bg_rawshape_cone(w2c_rapier__wasm3d__bg*, f32, f32);

/* export: 'rawshape_roundCone' */
u32 w2c_rapier__wasm3d__bg_rawshape_roundCone(w2c_rapier__wasm3d__bg*, f32, f32, f32);

/* export: 'rawshape_polyline' */
u32 w2c_rapier__wasm3d__bg_rawshape_polyline(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32);

/* export: 'rawshape_trimesh' */
u32 w2c_rapier__wasm3d__bg_rawshape_trimesh(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32);

/* export: 'rawshape_heightfield' */
u32 w2c_rapier__wasm3d__bg_rawshape_heightfield(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32);

/* export: 'rawshape_segment' */
u32 w2c_rapier__wasm3d__bg_rawshape_segment(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawshape_triangle' */
u32 w2c_rapier__wasm3d__bg_rawshape_triangle(w2c_rapier__wasm3d__bg*, u32, u32, u32);

/* export: 'rawshape_roundTriangle' */
u32 w2c_rapier__wasm3d__bg_rawshape_roundTriangle(w2c_rapier__wasm3d__bg*, u32, u32, u32, f32);

/* export: 'rawshape_convexHull' */
u32 w2c_rapier__wasm3d__bg_rawshape_convexHull(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'rawshape_roundConvexHull' */
u32 w2c_rapier__wasm3d__bg_rawshape_roundConvexHull(w2c_rapier__wasm3d__bg*, u32, u32, f32);

/* export: 'rawshape_convexMesh' */
u32 w2c_rapier__wasm3d__bg_rawshape_convexMesh(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32);

/* export: 'rawshape_roundConvexMesh' */
u32 w2c_rapier__wasm3d__bg_rawshape_roundConvexMesh(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, f32);

/* export: 'rawshape_castShape' */
u32 w2c_rapier__wasm3d__bg_rawshape_castShape(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, f32, u32);

/* export: 'rawshape_intersectsShape' */
u32 w2c_rapier__wasm3d__bg_rawshape_intersectsShape(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32);

/* export: 'rawshape_contactShape' */
u32 w2c_rapier__wasm3d__bg_rawshape_contactShape(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, f32);

/* export: 'rawshape_containsPoint' */
u32 w2c_rapier__wasm3d__bg_rawshape_containsPoint(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32);

/* export: 'rawshape_projectPoint' */
u32 w2c_rapier__wasm3d__bg_rawshape_projectPoint(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32);

/* export: 'rawshape_intersectsRay' */
u32 w2c_rapier__wasm3d__bg_rawshape_intersectsRay(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, f32);

/* export: 'rawshape_castRay' */
f32 w2c_rapier__wasm3d__bg_rawshape_castRay(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, f32, u32);

/* export: 'rawshape_castRayAndGetNormal' */
u32 w2c_rapier__wasm3d__bg_rawshape_castRayAndGetNormal(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, f32, u32);

/* export: '__wbg_rawshapetoi_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawshapetoi_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapetoi_witness1' */
u32 w2c_rapier__wasm3d__bg_rawshapetoi_witness1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapetoi_normal1' */
u32 w2c_rapier__wasm3d__bg_rawshapetoi_normal1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapetoi_normal2' */
u32 w2c_rapier__wasm3d__bg_rawshapetoi_normal2(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawshapecollidertoi_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawshapecollidertoi_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecollidertoi_witness2' */
u32 w2c_rapier__wasm3d__bg_rawshapecollidertoi_witness2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecollidertoi_normal2' */
u32 w2c_rapier__wasm3d__bg_rawshapecollidertoi_normal2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrotation_new' */
u32 w2c_rapier__wasm3d__bg_rawrotation_new(w2c_rapier__wasm3d__bg*, f32, f32, f32, f32);

/* export: 'rawrotation_identity' */
u32 w2c_rapier__wasm3d__bg_rawrotation_identity(w2c_rapier__wasm3d__bg*);

/* export: 'rawrotation_y' */
f32 w2c_rapier__wasm3d__bg_rawrotation_y(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrotation_w' */
f32 w2c_rapier__wasm3d__bg_rawrotation_w(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_zero' */
u32 w2c_rapier__wasm3d__bg_rawvector_zero(w2c_rapier__wasm3d__bg*);

/* export: 'rawvector_new' */
u32 w2c_rapier__wasm3d__bg_rawvector_new(w2c_rapier__wasm3d__bg*, f32, f32, f32);

/* export: 'rawvector_set_y' */
void w2c_rapier__wasm3d__bg_rawvector_set_y(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawvector_xyz' */
u32 w2c_rapier__wasm3d__bg_rawvector_xyz(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_yxz' */
u32 w2c_rapier__wasm3d__bg_rawvector_yxz(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_zxy' */
u32 w2c_rapier__wasm3d__bg_rawvector_zxy(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_xzy' */
u32 w2c_rapier__wasm3d__bg_rawvector_xzy(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_yzx' */
u32 w2c_rapier__wasm3d__bg_rawvector_yzx(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_zyx' */
u32 w2c_rapier__wasm3d__bg_rawvector_zyx(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawsdpmatrix3_elements' */
u32 w2c_rapier__wasm3d__bg_rawsdpmatrix3_elements(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawdebugrenderpipeline_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawdebugrenderpipeline_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdebugrenderpipeline_new' */
u32 w2c_rapier__wasm3d__bg_rawdebugrenderpipeline_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawdebugrenderpipeline_vertices' */
u32 w2c_rapier__wasm3d__bg_rawdebugrenderpipeline_vertices(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdebugrenderpipeline_colors' */
u32 w2c_rapier__wasm3d__bg_rawdebugrenderpipeline_colors(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdebugrenderpipeline_render' */
void w2c_rapier__wasm3d__bg_rawdebugrenderpipeline_render(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32);

/* export: '__wbg_raweventqueue_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_raweventqueue_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawcontactforceevent_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawcontactforceevent_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactforceevent_collider2' */
f64 w2c_rapier__wasm3d__bg_rawcontactforceevent_collider2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactforceevent_total_force' */
u32 w2c_rapier__wasm3d__bg_rawcontactforceevent_total_force(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactforceevent_total_force_magnitude' */
f32 w2c_rapier__wasm3d__bg_rawcontactforceevent_total_force_magnitude(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactforceevent_max_force_direction' */
u32 w2c_rapier__wasm3d__bg_rawcontactforceevent_max_force_direction(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactforceevent_max_force_magnitude' */
f32 w2c_rapier__wasm3d__bg_rawcontactforceevent_max_force_magnitude(w2c_rapier__wasm3d__bg*, u32);

/* export: 'raweventqueue_new' */
u32 w2c_rapier__wasm3d__bg_raweventqueue_new(w2c_rapier__wasm3d__bg*, u32);

/* export: 'raweventqueue_drainCollisionEvents' */
void w2c_rapier__wasm3d__bg_raweventqueue_drainCollisionEvents(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'raweventqueue_drainContactForceEvents' */
void w2c_rapier__wasm3d__bg_raweventqueue_drainContactForceEvents(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: 'raweventqueue_clear' */
void w2c_rapier__wasm3d__bg_raweventqueue_clear(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawphysicspipeline_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawphysicspipeline_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawphysicspipeline_new' */
u32 w2c_rapier__wasm3d__bg_rawphysicspipeline_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawphysicspipeline_step' */
void w2c_rapier__wasm3d__bg_rawphysicspipeline_step(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'rawphysicspipeline_stepWithEvents' */
void w2c_rapier__wasm3d__bg_rawphysicspipeline_stepWithEvents(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: '__wbg_rawquerypipeline_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawquerypipeline_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawquerypipeline_new' */
u32 w2c_rapier__wasm3d__bg_rawquerypipeline_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawquerypipeline_update' */
void w2c_rapier__wasm3d__bg_rawquerypipeline_update(w2c_rapier__wasm3d__bg*, u32, u32, u32);

/* export: 'rawquerypipeline_castRay' */
u32 w2c_rapier__wasm3d__bg_rawquerypipeline_castRay(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, f32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_castRayAndGetNormal' */
u32 w2c_rapier__wasm3d__bg_rawquerypipeline_castRayAndGetNormal(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, f32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_intersectionsWithRay' */
void w2c_rapier__wasm3d__bg_rawquerypipeline_intersectionsWithRay(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, f32, u32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_intersectionWithShape' */
void w2c_rapier__wasm3d__bg_rawquerypipeline_intersectionWithShape(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_projectPoint' */
u32 w2c_rapier__wasm3d__bg_rawquerypipeline_projectPoint(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_projectPointAndGetFeature' */
u32 w2c_rapier__wasm3d__bg_rawquerypipeline_projectPointAndGetFeature(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_intersectionsWithPoint' */
void w2c_rapier__wasm3d__bg_rawquerypipeline_intersectionsWithPoint(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_castShape' */
u32 w2c_rapier__wasm3d__bg_rawquerypipeline_castShape(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, f32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_intersectionsWithShape' */
void w2c_rapier__wasm3d__bg_rawquerypipeline_intersectionsWithShape(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, f64, u32, f64, u32);

/* export: 'rawquerypipeline_collidersWithAabbIntersectingAabb' */
void w2c_rapier__wasm3d__bg_rawquerypipeline_collidersWithAabbIntersectingAabb(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32);

/* export: '__wbg_rawdeserializedworld_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawdeserializedworld_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeGravity' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeGravity(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeIntegrationParameters' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeIntegrationParameters(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeIslandManager' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeIslandManager(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeBroadPhase' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeBroadPhase(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeNarrowPhase' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeNarrowPhase(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeBodies' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeBodies(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeColliders' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeColliders(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeImpulseJoints' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeImpulseJoints(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawdeserializedworld_takeMultibodyJoints' */
u32 w2c_rapier__wasm3d__bg_rawdeserializedworld_takeMultibodyJoints(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawserializationpipeline_serializeAll' */
u32 w2c_rapier__wasm3d__bg_rawserializationpipeline_serializeAll(w2c_rapier__wasm3d__bg*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'rawserializationpipeline_deserializeAll' */
u32 w2c_rapier__wasm3d__bg_rawserializationpipeline_deserializeAll(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbg_rawcontactpair_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawcontactpair_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawraycolliderintersection_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawraycolliderintersection_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawrotation_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawrotation_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawvector_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawvector_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawsdpmatrix3_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawsdpmatrix3_free(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_set_x' */
void w2c_rapier__wasm3d__bg_rawvector_set_x(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawvector_set_z' */
void w2c_rapier__wasm3d__bg_rawvector_set_z(w2c_rapier__wasm3d__bg*, u32, f32);

/* export: 'rawpointprojection_isInside' */
u32 w2c_rapier__wasm3d__bg_rawpointprojection_isInside(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawpointcolliderprojection_isInside' */
u32 w2c_rapier__wasm3d__bg_rawpointcolliderprojection_isInside(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcolliderset_isHandleValid' */
u32 w2c_rapier__wasm3d__bg_rawcolliderset_isHandleValid(w2c_rapier__wasm3d__bg*, u32, f64);

/* export: 'rawshapecontact_point1' */
u32 w2c_rapier__wasm3d__bg_rawshapecontact_point1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecontact_point2' */
u32 w2c_rapier__wasm3d__bg_rawshapecontact_point2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecontact_normal2' */
u32 w2c_rapier__wasm3d__bg_rawshapecontact_normal2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawpointprojection_point' */
u32 w2c_rapier__wasm3d__bg_rawpointprojection_point(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawpointcolliderprojection_point' */
u32 w2c_rapier__wasm3d__bg_rawpointcolliderprojection_point(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrayintersection_normal' */
u32 w2c_rapier__wasm3d__bg_rawrayintersection_normal(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecollidertoi_witness1' */
u32 w2c_rapier__wasm3d__bg_rawshapecollidertoi_witness1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecontact_normal1' */
u32 w2c_rapier__wasm3d__bg_rawshapecontact_normal1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecollidertoi_normal1' */
u32 w2c_rapier__wasm3d__bg_rawshapecollidertoi_normal1(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapetoi_witness2' */
u32 w2c_rapier__wasm3d__bg_rawshapetoi_witness2(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawserializationpipeline_new' */
u32 w2c_rapier__wasm3d__bg_rawserializationpipeline_new(w2c_rapier__wasm3d__bg*);

/* export: 'rawintegrationparameters_erp' */
f32 w2c_rapier__wasm3d__bg_rawintegrationparameters_erp(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrayintersection_toi' */
f32 w2c_rapier__wasm3d__bg_rawrayintersection_toi(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawraycollidertoi_toi' */
f32 w2c_rapier__wasm3d__bg_rawraycollidertoi_toi(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapetoi_toi' */
f32 w2c_rapier__wasm3d__bg_rawshapetoi_toi(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecollidertoi_toi' */
f32 w2c_rapier__wasm3d__bg_rawshapecollidertoi_toi(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrotation_x' */
f32 w2c_rapier__wasm3d__bg_rawrotation_x(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawrotation_z' */
f32 w2c_rapier__wasm3d__bg_rawrotation_z(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_x' */
f32 w2c_rapier__wasm3d__bg_rawvector_x(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_y' */
f32 w2c_rapier__wasm3d__bg_rawvector_y(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawvector_z' */
f32 w2c_rapier__wasm3d__bg_rawvector_z(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawraycolliderintersection_colliderHandle' */
f64 w2c_rapier__wasm3d__bg_rawraycolliderintersection_colliderHandle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawraycollidertoi_colliderHandle' */
f64 w2c_rapier__wasm3d__bg_rawraycollidertoi_colliderHandle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawshapecollidertoi_colliderHandle' */
f64 w2c_rapier__wasm3d__bg_rawshapecollidertoi_colliderHandle(w2c_rapier__wasm3d__bg*, u32);

/* export: 'rawcontactforceevent_collider1' */
f64 w2c_rapier__wasm3d__bg_rawcontactforceevent_collider1(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbg_rawserializationpipeline_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbg_rawserializationpipeline_free(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbindgen_add_to_stack_pointer' */
u32 w2c_rapier__wasm3d__bg_0x5F_wbindgen_add_to_stack_pointer(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbindgen_free' */
void w2c_rapier__wasm3d__bg_0x5F_wbindgen_free(w2c_rapier__wasm3d__bg*, u32, u32);

/* export: '__wbindgen_malloc' */
u32 w2c_rapier__wasm3d__bg_0x5F_wbindgen_malloc(w2c_rapier__wasm3d__bg*, u32);

/* export: '__wbindgen_exn_store' */
void w2c_rapier__wasm3d__bg_0x5F_wbindgen_exn_store(w2c_rapier__wasm3d__bg*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* RAPIER_WASM3D_BG_H_GENERATED_ */
