//
// THIS FILE WAS GENERATED BY `react-native-wasm`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#pragma once
#include <ReactNativePolygen/StaticLibraryModule.h>

namespace facebook::react {

std::shared_ptr<Module> createRapier__wasm3d__bgModule();

class WASMRapier__wasm3d__bgModule: public StaticLibraryModule {
public:
  WASMRapier__wasm3d__bgModule(const std::string& name): StaticLibraryModule(name) {}
  const std::vector<ImportInfo>& getImports() const override;
  const std::vector<ExportInfo>& getExports() const override;
  jsi::Object createInstance(jsi::Runtime& rt, jsi::Object&& importObject) const override;
};

}
  