export const CAM_VIDEO_CHANGED = 'CAM_VIDEO_CHANGED';
export const CAM_AUDIO_CHANGED = 'CAM_AUDIO_CHANGED';
export const FACE_TRACKING_CHANGED = 'FACE_TRACKING_CHANGED';
export const SCREEN_VIDEO_CHANGED = 'SCREEN_VIDEO_CHANGED';
export const SCREEN_AUDIO_CHANGED = 'SCREEN_AUDIO_CHANGED';
export const CONSUMERS_CHANGED = 'CONSUMERS_CHANGED';

export const CHANNEL_TYPE_CHANGED = 'CHANNEL_TYPE_CHANGED';