import { Engine } from '../../ecs/classes/Engine'
import { World } from '../../ecs/classes/World'
import { Network } from '../classes/Network'
import { NetworkPeerFunctions } from './NetworkPeerFunctions'
import { updatePeers } from './SocketWebRTCServerFunctions'
