export declare function insertSeparator(children: any, separatorFn: any): any;
export declare function objectToMap(object: object): Map<string, any>;
export declare function unique(arr: any, maybeComp: any): any[];
export declare const isApple: boolean;
export declare const cmdOrCtrlString: string;
export declare function getStepSize(event: any, smallStep: any, mediumStep: any, largeStep: any): any;
export declare function clamp(value: any, min: any, max: any): any;
export declare function toPrecision(value: any, precision: any): number;
export declare function camelPad(str: any): any;
export declare function bytesToSize(bytes: any): string;
