// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Invite = sequelize.define('invite', {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    token: {
      type: DataTypes.STRING,
    },
    identityProviderType: {
      type: DataTypes.STRING,
    },
    passcode: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    targetObjectId: {
      type: DataTypes.STRING,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'invite',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Invite.associate = (models) => {
    Invite.belongsTo(models.inviteType, {
      foreignKey: {
        name: 'inviteTypeKey',
        field: 'inviteType',
      },
      targetKey: 'type',
      as: 'inviteType',
    });
    Invite.belongsTo(models.user, {
      foreignKey: {
        name: 'inviteeIdKey',
        field: 'inviteeId',
      },
      as: 'invitee',
    });
    Invite.belongsTo(models.user, {
      foreignKey: {
        name: 'userIdKey',
        field: 'userId',
      },
      as: 'user',
    });
  };

  return Invite;
};
