// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Message = sequelize.define('message', {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    text: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'message',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Message.associate = (models) => {
    Message.belongsTo(models.channel, {
      foreignKey: {
        name: 'channelIdKey',
        field: 'channelId',
      },
      as: 'channel',
    });
    Message.belongsTo(models.user, {
      foreignKey: {
        name: 'senderIdKey',
        field: 'senderId',
      },
      as: 'sender',
    });
    Message.hasMany(models.messageStatus, {
      foreignKey: {
        name: 'messageIdKey',
        field: 'messageId',
      },
      as: 'messageStatuses',
    });
  };

  return Message;
};
