// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Party = sequelize.define('party', {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'party',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Party.associate = (models) => {
    Party.belongsTo(models.instance, {
      foreignKey: {
        name: 'instanceIdKey',
        field: 'instanceId',
      },
      as: 'instance',
    });
    Party.belongsTo(models.location, {
      foreignKey: {
        name: 'locationIdKey',
        field: 'locationId',
      },
      as: 'location',
    });
    Party.hasMany(models.user, {
      foreignKey: {
        name: 'partyIdKey',
        field: 'partyId',
      },
      as: 'users',
    });
    Party.hasMany(models.partyUser, {
      foreignKey: {
        name: 'partyIdKey',
        field: 'partyId',
      },
      as: 'partyUsers',
    });
    Party.hasMany(models.channel, {
      foreignKey: {
        name: 'partyIdKey',
        field: 'partyId',
      },
      as: 'channels',
    });
  };

  return Party;
};
