// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SubscriptionLevel = sequelize.define('subscriptionLevel', {
    level: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'subscription_level',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  SubscriptionLevel.associate = (models) => {
    SubscriptionLevel.hasMany(models.staticResource, {
      foreignKey: {
        name: 'subscriptionLevelKey',
        field: 'subscriptionLevel',
      },
      sourceKey: 'level',
      as: 'subscriptionLevelStaticResources',
    });
  };

  return SubscriptionLevel;
};
