import config from '../../appconfig'

export const componentTypeSeed = {
  path: 'component-type',
  randomize: false,
  templates: [
    { type: 'ambient-light' },
    { type: 'animation' },
    { type: 'audio-settings' },
    { type: 'background' },
    { type: 'box-collider' },
    { type: 'camera' },
    { type: 'cursor' },
    { type: 'debug' },
    { type: 'device-orientation-permission-ui' },
    { type: 'embedded' },
    { type: 'fog' },
    { type: 'geometry' },
    { type: 'gltf-model' },
    { type: 'gltf-shopify' },
    { type: 'ground' },
    { type: 'ground-plane' },
    { type: 'hand-controls' },
    { type: 'keyboard-shortcuts' },
    { type: 'laser-controls' },
    { type: 'light' },
    { type: 'line' },
    { type: 'link' },
    { type: 'loading-screen' },
    { type: 'look-controls' },
    { type: 'networked' },
    { type: 'obj-model' },
    { type: 'oculus-go-controls' },
    { type: 'pool' },
    { type: 'position' },
    { type: 'raycaster' },
    { type: 'renderer' },
    { type: 'rotation' },
    { type: 'scale' },
    { type: 'scene-preview-camera' },
    { type: 'screenshot' },
    { type: 'shadow' },
    { type: 'skybox' },
    { type: 'sound' },
    { type: 'stats' },
    { type: 'text' },
    { type: 'tracked-controls' },
    { type: 'transform' },
    { type: 'visible' },
    { type: 'vive-controls' },
    { type: 'vive-focus-controls' },
    { type: 'vr-mode-ui' },
    { type: 'wasd-controls' },
    { type: 'windows-motion-controls' },
    // Custom Components
    { type: 'walkable' },
    { type: 'grid' }
  ]
}
