name: Installation Tech Support
description: I'm having difficulty installing Infinite Reality Engine
title: '[Ticket]: '
labels: '[ticket]'
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using Infinite Reality Engine! Let's figure out the problem.
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you trying to install on?
    validations:
      required: true
  - type: input
    id: nodev
    attributes:
      label: Node Version
      description: What nodejs version are you using? (run `node -v` if you are unsure)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue you are facing.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
