// TODO: Abstract so this is user / data driven and not hardcoded

enum AxisValue {
  MOVEMENT_IDLE,
  MOVEMENT_WALKING_FORWARD,
  MOVEMENT_JOGGING_FORWARD,
  MOVEMENT_RUNNING_FORWARD,
  MOVEMENT_WALKING_BACKWARD,
  MOVEMENT_JOGGING_BACKWARD,
  MOVEMENT_STRAFING_RIGHT,
  MOVEMENT_STRAFING_LEFT,
  MOVEMENT_RUNNING_BACKWARD
}

export default AxisValue
