const Axes = {
  SCREENXY: 0,
  DPADONE: 1,
  DPADTWO: 2,
  DPADTHREE: 3,
  DPADFOUR: 4,
  MOVEMENT_IDLE: 0,
  MOVEMENT_WALKING_FORWARD: 11,
  MOVEMENT_JOGGING_FORWARD: 12,
  MOVEMENT_RUNNING_FORWARD: 13,
  MOVEMENT_WALKING_BACKWARD: 14,
  MOVEMENT_JOGGING_BACKWARD: 15,
  MOVEMENT_STRAFING_RIGHT: 16,
  MOVEMENT_STRAFING_LEFT: 17,
  MOVEMENT_RUNNING_BACKWARD: 18
}

export default Axes
