// Abstract inputs that all input devices get mapped to

export enum BaseInput {
  PRIMARY = 'BaseInput_PRIMARY',
  SECONDARY = 'BaseInput_SECONDARY',
  FORWARD = 'BaseInput_FORWARD',
  BACKWARD = 'BaseInput_BACKWARD',
  UP = 'BaseInput_UP',
  DOWN = 'BaseInput_DOWN',
  LEFT = 'BaseInput_LEFT',
  RIGHT = 'BaseInput_RIGHT',
  INTERACT = 'BaseInput_INTERACT',
  DROP_OBJECT = 'BaseInput_DROP_OBJECT',
  GRAB_LEFT = 'BaseInput_GRAB_LEFT',
  GRAB_RIGHT = 'BaseInput_GRAB_RIGHT',
  JUMP = 'BaseInput_JUMP',
  RUN = 'BaseInput_RUN',
  SCREENXY = 'BaseInput_SCREENXY',
  PRIMARY_MOVE_LEFT = 'BaseInput_PRIMARY_MOVE_LEFT',
  PRIMARY_MOVE_RIGHT = 'BaseInput_PRIMARY_MOVE_RIGHT',
  POINTER_LOCK = 'BaseInput_POINTER_LOCK',
  CAMERA_SCROLL = 'BaseInput_CAMERA_SCROLL',
  CAMERA_ROTATE_RIGHT = 'BaseInput_CAMERA_ROTATE_RIGHT',
  CAMERA_ROTATE_LEFT = 'BaseInput_CAMERA_ROTATE_LEFT',
  SWITCH_CAMERA = 'BaseInput_SWITCH_CAMERA',
  LOCKING_CAMERA = 'BaseInput_LOCKING_CAMERA',
  SWITCH_SHOULDER_SIDE = 'BaseInput_SWITCH_SHOULDER_SIDE',
  GRIP_LEFT = 'BaseInput_GRIP_LEFT',
  GRIP_RIGHT = 'BaseInput_GRIP_RIGHT',
  TOGGLE_MENU_BUTTONS = 'BaseInput_TOGGLE_MENU_BUTTONS'
}
