export enum PhysicsDebugInput {
  GENERATE_DYNAMIC_DEBUG_CUBE = 'GENERATE_DYNAMIC_DEBUG_CUBE',
  TOGGLE_PHYSICS_DEBUG = 'TOGGLE_PHYSICS_DEBUG'
}
export enum NavigationDebugInput {
  TOGGLE_NAVIGATION_DEBUG = 'TOGGLE_NAVIGATION_DEBUG'
}
