import { Box2 as _Box2, Box3 as _Box3, Color as _Color, Cylindrical as _Cylindrical, Euler as _Euler, Frustum as _Frustum, Line3 as _Line3, Matrix3 as _Matrix3, Matrix4 as _Matrix4, Plane as _Plane, Quaternion as _Quaternion, Ray as _Ray, Sphere as _Sphere, Spherical as _Spherical, SphericalHarmonics3 as _SphericalHarmonics3, Triangle as _Triangle, Vector2 as _Vector2, Vector3 as _Vector3, Vector4 as _Vector4 } from 'three';
import { PropType } from '../../ecs/types/Types';
export declare type Box2Type = PropType<_Box2, _Box2>;
export declare type Box3Type = PropType<_Box3, _Box3>;
export declare type ColorType = PropType<_Color, _Color>;
export declare type CylindricalType = PropType<_Cylindrical, _Cylindrical>;
export declare type EulerType = PropType<_Euler, _Euler>;
export declare type FrustumType = PropType<_Frustum, _Frustum>;
export declare type Line3Type = PropType<_Line3, _Line3>;
export declare type Matrix3Type = PropType<_Matrix3, _Matrix3>;
export declare type Matrix4Type = PropType<_Matrix4, _Matrix4>;
export declare type PlaneType = PropType<_Plane, _Plane>;
export declare type QuaternionType = PropType<_Quaternion, _Quaternion>;
export declare type RayType = PropType<_Ray, _Ray>;
export declare type SphereType = PropType<_Sphere, _Sphere>;
export declare type SphericalType = PropType<_Spherical, _Spherical>;
export declare type SphericalHarmonics3Type = PropType<_SphericalHarmonics3, _SphericalHarmonics3>;
export declare type TriangleType = PropType<_Triangle, _Triangle>;
export declare type Vector2Type = PropType<_Vector2, _Vector2>;
export declare type Vector3Type = PropType<_Vector3, _Vector3>;
export declare type Vector4Type = PropType<_Vector4, _Vector4>;
