//
// THIS FILE WAS GENERATED BY `react-native-wasm`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//
#pragma once
#include <span>
#include <memory>
#include <string>
#include <vector>
#include <jsi/jsi.h>
#include <ReactNativePolygen/Module.h>

namespace facebook::react {

const std::vector<std::string>& getAvailableModules();
std::shared_ptr<Module> loadWebAssemblyModule(std::span<uint8_t> moduleData);

}
  