//
// THIS FILE WAS GENERATED BY `polygen`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#include <sstream>
#include <ReactNativePolygen/w2c.h>
#include <ReactNativePolygen/checksum.h>
#include <ReactNativePolygen/bridge.h>

namespace callstack::polygen::generated {

using ModuleFactoryFunction = std::function<std::shared_ptr<Module>()>;

std::shared_ptr<Module> createMeshopt__decoderModule();
std::shared_ptr<Module> createRapier__wasm3d__bgModule();

const std::vector<std::string> moduleNames { "meshopt_decoder", "rapier_wasm3d_bg" };
// TODO: skip in release
const std::unordered_map<std::string, std::string> moduleChecksums {
  { "meshopt_decoder", "66f423625b08f528cfa06c88457988394e0f15c4f3f478c5139399adc1f6e00b" },
  { "rapier_wasm3d_bg", "425749aa8b9c239ffd1958ac5c9c1184590278b53c1c676c7509a1511bc8b7d2" }
};
std::unordered_map<std::string, ModuleFactoryFunction> moduleFactoryByChecksum {
  { "66f423625b08f528cfa06c88457988394e0f15c4f3f478c5139399adc1f6e00b", createMeshopt__decoderModule },
  { "425749aa8b9c239ffd1958ac5c9c1184590278b53c1c676c7509a1511bc8b7d2", createRapier__wasm3d__bgModule }
};

const std::vector<std::string>& getAvailableModules() {
  return moduleNames;
}

std::shared_ptr<Module> loadWebAssemblyModule(std::span<uint8_t> moduleData) {
  if (ModuleMetadataView::isMetadata(moduleData)) {
    auto metadata = ModuleMetadataView::fromBuffer(moduleData);
    auto& name = metadata->getName();

    // TODO: skip in release
    if (auto foundModule = moduleChecksums.find(metadata->checksum); foundModule != moduleChecksums.end()) {
      std::ostringstream errorMsgStream;
      errorMsgStream << "Module checksums for '" << name << "' differ, this means that the precompiled module is different from the one that was generated. Perhaps you forgot to rebuild the project?";
      throw LoaderError { errorMsgStream.str() };
    }

    if (name == "meshopt_decoder") { return createMeshopt__decoderModule(); }
    if (name == "rapier_wasm3d_bg") { return createRapier__wasm3d__bgModule(); }
    std::ostringstream errorMsgStream;
    errorMsgStream << "Failed to load WebAssembly Module '" << name << "'. The module is not precompiled. Perhaps you forgot to run 'polygen generate'?";
    throw LoaderError { errorMsgStream.str() };
  } else {
    auto checksum = computeSHA256(moduleData);
    if (auto foundModule = moduleFactoryByChecksum.find(checksum); foundModule != moduleFactoryByChecksum.end()) {
      return foundModule->second();
    }

    throw LoaderError { "Tried to load an unknown WebAssembly Module from binary buffer. Polygen can only load statically precompilied modules." };
  }
}

}
  