//
// THIS FILE WAS GENERATED BY `react-native-wasm`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#include "loader.h"
#include <ReactNativePolygen/w2c.h>

const std::vector<std::string> moduleNames { "rapier_wasm3d_bg" };

std::unordered_map<std::string, std::string> moduleByChecksum {
  { "425749aa8b9c239ffd1958ac5c9c1184590278b53c1c676c7509a1511bc8b7d2", "rapier_wasm3d_bg" }
};

namespace facebook::react {

const std::vector<std::string>& getAvailableModules() {
  return moduleNames;
}

std::unique_ptr<Module> createRapier__wasm3d__bgModule();

std::shared_ptr<Module> loadWebAssemblyModule(std::span<uint8_t> moduleData) {
  auto metadata = ModuleMetadataView::fromBuffer(moduleData);
  auto& name = metadata.name;
  if (name == "rapier_wasm3d_bg") { return createRapier__wasm3d__bgModule(); }
  return nullptr;
}
}
  