// https://developers.google.com/mediapipe/solutions/vision/pose_landmarker
const mediapipePoseNames = [
  'nose',
  'left eye inner',
  'left eye',
  'left eye outer',
  'right eye inner',
  'right eye',
  'right eye outer',
  'left ear',
  'right ear',
  'mouth (left)',
  'mouth (right)',
  'left shoulder',
  'right shoulder',
  'left elbow',
  'right elbow',
  'left wrist',
  'right wrist',
  'left pinky',
  'right pinky',
  'left index',
  'right index',
  'left thumb',
  'right thumb',
  'left hip',
  'right hip',
  'left knee',
  'right knee',
  'left ankle',
  'right ankle',
  'left heel',
  'right heel',
  'left foot index',
  'right foot index'
]

export default mediapipePoseNames
