
let potEstimator: (ovr: number, age: number, pos?: string) => number;

// This was generated by using bootstrapPot a bunch of times and then doing linear regression to find the
// coefficients for predicting pot. For basketball, it is only used in one place.

// See analysis/pot-estimator-basketball
potEstimator = (ovr: number, age: number) => {
	if (age >= 29) {
		return ovr;
	}

	return 72.31428908571982 + -2.33062761 * age + 0.83308748 * ovr;
};

export default potEstimator;
