/** List of Asset Types. */
export enum AssetType {
  XRE = 'xre.gltf',
  glB = 'glb',
  glTF = 'gltf',
  FBX = 'fbx',
  OBJ = 'obj',
  VRM = 'vrm',
  PNG = 'png',
  JPEG = 'jpeg',
  TGA = 'tga',
  MP4 = 'mp4',
  TS = 'ts',
  MKV = 'mkv',
  MP3 = 'mp3',
  OGG = 'ogg',
  M4A = 'm4a',
  AAC = 'acc',
  CSV = 'csv',
  PlainText = 'text',
  DOC = 'doc',
  XLS = 'xls',
  Script = 'script',
  KTX2 = 'ktx2',
  USDZ = 'usdz'
}
