// Auth Actions
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const LOADED_USER_DATA = 'LOADED_USER_DATA'

export const ACTION_PROCESSING = 'ACTION_PROCESSING'

export const LOGIN_USER_BY_GITHUB_SUCCESS = 'LOGIN_USER_BY_GITHUB_SUCCESS'
export const LOGIN_USER_BY_GITHUB_ERROR = 'LOGIN_USER_BY_GITHUB_ERROR'

export const LOGIN_USER_BY_LINKEDIN_SUCCESS = 'LOGIN_USER_BY_LINKEDIN_SUCCESS'
export const LOGIN_USER_BY_LINKEDIN_ERROR = 'LOGIN_USER_BY_LINKEDIN_ERROR'

export const LOGIN_USER_BY_FACEBOOK_SUCCESS = 'LOGIN_USER_BY_FACEBOOK_SUCCESS'
export const LOGIN_USER_BY_FACEBOOK_ERROR = 'LOGIN_USER_BY_FACEBOOK_ERROR'

export const LOGIN_USER_BY_GOOGLE_SUCCESS = 'LOGIN_USER_BY_GOOGLE_SUCCESS'
export const LOGIN_USER_BY_GOOGLE_ERROR = 'LOGIN_USER_BY_GOOGLE_ERROR'

export const REGISTER_USER_BY_EMAIL_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_BY_EMAIL_ERROR = 'REGISTER_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

export const DID_VERIFY_EMAIL = 'DID_VERIFY_EMAIL'
export const DID_RESEND_VERIFICATION_EMAIL = 'DID_RESEND_VERIFICATION_EMAIL'
export const DID_FORGOT_PASSWORD = 'DID_FORGOT_PASSWORD'
export const DID_RESET_PASSWORD = 'DID_RESET_PASSWORD'

export const VIDEOS_FETCHED_SUCCESS = 'VIDEOS_FETCHED_SUCCESS'
export const VIDEOS_FETCHED_ERROR = 'VIDEOS_FETCHED_ERROR'

export const DID_CREATE_MAGICLINK = 'DID_CREATE_MAGICLINK'

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION'
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION'

export const RESTORE = 'RESTORE'

export const AVATAR_FETCHED = 'AVATAR_FETCHED'
export const AVATAR_UPDATED = 'AVATAR_UPDATED'
export const AVATAR_UPDATE_FAILURE = 'AVATAR_UPDATE_FAILURE'
export const USER_UPDATED = 'USER_UPDATED'
export const USERNAME_UPDATED = 'USERNAME_UPDATED'
export const USERAVATARID_UPDATED = 'USERAVATARID_UPDATED'

export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS'

export const UPDATE_USER_SETTINGS_FALURE = 'UPDATE_USER_SETTINGS_FALURE'

export const DETECT_DEVICE_TYPE = 'DETECT_DEVICE_TYPE'

//USERS
export const USER_CREATED = 'USER_CREATED'
export const USER_REMOVED_ROW = 'USER_REMOVED_ROW'
export const USER_PATCHED = 'USER_PATCHED'
