//
// THIS FILE WAS GENERATED BY `react-native-wasm`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#pragma once
#include "meshopt_decoder.h"


namespace callstack::polygen::generated {

class Meshopt__decoderModuleContext: public facebook::jsi::NativeState {
public:
  Meshopt__decoderModuleContext(facebook::jsi::Runtime& rt, facebook::jsi::Object&& importObject)
    : importObject(std::move(importObject))
    
  {}

  facebook::jsi::Object importObject;
  w2c_meshopt__decoder rootCtx;
  
};

void createMeshopt__decoderExports(facebook::jsi::Runtime &rt, facebook::jsi::Object& target, facebook::jsi::Object&& importObject);

}
