//
// THIS FILE WAS GENERATED BY `polygen`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#include <ReactNativePolygen/gen-utils.h>
#include <ReactNativePolygen/WebAssembly.h>
#include "jsi-exports-bridge.h"
#include "wasm-rt.h"
#include "meshopt_decoder.h"

using namespace facebook;
using namespace callstack::polygen;

namespace callstack::polygen::generated {
  void createMeshopt__decoderExports(jsi::Runtime &rt, jsi::Object& target, jsi::Object&& importObject) {
    if (!wasm_rt_is_initialized()) {
      wasm_rt_init();
    }

    auto inst = std::make_shared<Meshopt__decoderModuleContext>(rt, std::move(importObject));
    wasm2c_meshopt__decoder_instantiate(&inst->rootCtx);

    target.setNativeState(rt, inst);

    // Memories
    jsi::Object memories {rt};
    
  /* exported memory: 'memory' */
  {
    jsi::Object holder {rt};
    auto memory = std::make_shared<Memory>(w2c_meshopt__decoder_memory(&inst->rootCtx));
    holder.setNativeState(rt, std::move(memory));
    memories.setProperty(rt, "memory", std::move(holder));
  }

    target.setProperty(rt, "memories", std::move(memories));

    // Tables
    jsi::Object tables {rt};
    
    target.setProperty(rt, "tables", std::move(tables));

    // Exported functions
    jsi::Object exports {rt};
    
  /* export: '__wasm_call_ctors' */
  exports.setProperty(rt, "__wasm_call_ctors", HOSTFN("__wasm_call_ctors", 0) {
    w2c_meshopt__decoder_0x5F_wasm_call_ctors(&inst->rootCtx);
    return jsi::Value::undefined();
  }));

    
  /* export: 'meshopt_decodeVertexBuffer' */
  exports.setProperty(rt, "meshopt_decodeVertexBuffer", HOSTFN("meshopt_decodeVertexBuffer", 5) {
    auto res = w2c_meshopt__decoder_meshopt_decodeVertexBuffer(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])), std::bit_cast<u32>(coerceToNumber<s32>(args[1])), std::bit_cast<u32>(coerceToNumber<s32>(args[2])), std::bit_cast<u32>(coerceToNumber<s32>(args[3])), std::bit_cast<u32>(coerceToNumber<s32>(args[4])));
    return jsi::Value { (double)std::bit_cast<s32>(res) };
  }));

    
  /* export: 'meshopt_decodeIndexBuffer' */
  exports.setProperty(rt, "meshopt_decodeIndexBuffer", HOSTFN("meshopt_decodeIndexBuffer", 5) {
    auto res = w2c_meshopt__decoder_meshopt_decodeIndexBuffer(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])), std::bit_cast<u32>(coerceToNumber<s32>(args[1])), std::bit_cast<u32>(coerceToNumber<s32>(args[2])), std::bit_cast<u32>(coerceToNumber<s32>(args[3])), std::bit_cast<u32>(coerceToNumber<s32>(args[4])));
    return jsi::Value { (double)std::bit_cast<s32>(res) };
  }));

    
  /* export: 'meshopt_decodeIndexSequence' */
  exports.setProperty(rt, "meshopt_decodeIndexSequence", HOSTFN("meshopt_decodeIndexSequence", 5) {
    auto res = w2c_meshopt__decoder_meshopt_decodeIndexSequence(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])), std::bit_cast<u32>(coerceToNumber<s32>(args[1])), std::bit_cast<u32>(coerceToNumber<s32>(args[2])), std::bit_cast<u32>(coerceToNumber<s32>(args[3])), std::bit_cast<u32>(coerceToNumber<s32>(args[4])));
    return jsi::Value { (double)std::bit_cast<s32>(res) };
  }));

    
  /* export: 'meshopt_decodeFilterOct' */
  exports.setProperty(rt, "meshopt_decodeFilterOct", HOSTFN("meshopt_decodeFilterOct", 3) {
    w2c_meshopt__decoder_meshopt_decodeFilterOct(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])), std::bit_cast<u32>(coerceToNumber<s32>(args[1])), std::bit_cast<u32>(coerceToNumber<s32>(args[2])));
    return jsi::Value::undefined();
  }));

    
  /* export: 'meshopt_decodeFilterQuat' */
  exports.setProperty(rt, "meshopt_decodeFilterQuat", HOSTFN("meshopt_decodeFilterQuat", 3) {
    w2c_meshopt__decoder_meshopt_decodeFilterQuat(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])), std::bit_cast<u32>(coerceToNumber<s32>(args[1])), std::bit_cast<u32>(coerceToNumber<s32>(args[2])));
    return jsi::Value::undefined();
  }));

    
  /* export: 'meshopt_decodeFilterExp' */
  exports.setProperty(rt, "meshopt_decodeFilterExp", HOSTFN("meshopt_decodeFilterExp", 3) {
    w2c_meshopt__decoder_meshopt_decodeFilterExp(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])), std::bit_cast<u32>(coerceToNumber<s32>(args[1])), std::bit_cast<u32>(coerceToNumber<s32>(args[2])));
    return jsi::Value::undefined();
  }));

    
  /* export: 'sbrk' */
  exports.setProperty(rt, "sbrk", HOSTFN("sbrk", 1) {
    auto res = w2c_meshopt__decoder_sbrk(&inst->rootCtx, std::bit_cast<u32>(coerceToNumber<s32>(args[0])));
    return jsi::Value { (double)std::bit_cast<s32>(res) };
  }));

    exports.setNativeState(rt, inst);
    target.setProperty(rt, "exports", std::move(exports));
  }
}
  