/* Automatically generated by wasm2c */
#ifndef MESHOPT_DECODER_H_GENERATED_
#define MESHOPT_DECODER_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_meshopt__decoder {
  u32 w2c_g0;
  wasm_rt_memory_t w2c_memory;
} w2c_meshopt__decoder;

void wasm2c_meshopt__decoder_instantiate(w2c_meshopt__decoder*);
void wasm2c_meshopt__decoder_free(w2c_meshopt__decoder*);
wasm_rt_func_type_t wasm2c_meshopt__decoder_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'memory' */
wasm_rt_memory_t* w2c_meshopt__decoder_memory(w2c_meshopt__decoder* instance);

/* export: '__wasm_call_ctors' */
void w2c_meshopt__decoder_0x5F_wasm_call_ctors(w2c_meshopt__decoder*);

/* export: 'meshopt_decodeVertexBuffer' */
u32 w2c_meshopt__decoder_meshopt_decodeVertexBuffer(w2c_meshopt__decoder*, u32, u32, u32, u32, u32);

/* export: 'meshopt_decodeIndexBuffer' */
u32 w2c_meshopt__decoder_meshopt_decodeIndexBuffer(w2c_meshopt__decoder*, u32, u32, u32, u32, u32);

/* export: 'meshopt_decodeIndexSequence' */
u32 w2c_meshopt__decoder_meshopt_decodeIndexSequence(w2c_meshopt__decoder*, u32, u32, u32, u32, u32);

/* export: 'meshopt_decodeFilterOct' */
void w2c_meshopt__decoder_meshopt_decodeFilterOct(w2c_meshopt__decoder*, u32, u32, u32);

/* export: 'meshopt_decodeFilterQuat' */
void w2c_meshopt__decoder_meshopt_decodeFilterQuat(w2c_meshopt__decoder*, u32, u32, u32);

/* export: 'meshopt_decodeFilterExp' */
void w2c_meshopt__decoder_meshopt_decodeFilterExp(w2c_meshopt__decoder*, u32, u32, u32);

/* export: 'sbrk' */
u32 w2c_meshopt__decoder_sbrk(w2c_meshopt__decoder*, u32);

#ifdef __cplusplus
}
#endif

#endif  /* MESHOPT_DECODER_H_GENERATED_ */
