//
// THIS FILE WAS GENERATED BY `polygen`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#pragma once
#include <ReactNativePolygen/StaticLibraryModule.h>

namespace callstack::polygen::generated {

std::shared_ptr<callstack::polygen::Module> createMeshopt__decoderModule();

class WASMMeshopt__decoderModule: public callstack::polygen::StaticLibraryModule {
public:
  WASMMeshopt__decoderModule(const std::string& name): StaticLibraryModule(name) {}
  const std::vector<ImportInfo>& getImports() const override;
  const std::vector<ExportInfo>& getExports() const override;
  void createInstance(facebook::jsi::Runtime& rt, facebook::jsi::Object& target, facebook::jsi::Object&& importObject) const override;
};

}
  