//
// THIS FILE WAS GENERATED BY `polygen`
//
// DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST.
//

#include "static-module.h"
#include "jsi-exports-bridge.h"

using namespace facebook;

namespace callstack::polygen::generated {

const std::vector<Module::ImportInfo> imports {  };
const std::vector<Module::ExportInfo> exports { {"memory", Module::SymbolKind::Memory}, {"__wasm_call_ctors", Module::SymbolKind::Function}, {"meshopt_decodeVertexBuffer", Module::SymbolKind::Function}, {"meshopt_decodeIndexBuffer", Module::SymbolKind::Function}, {"meshopt_decodeIndexSequence", Module::SymbolKind::Function}, {"meshopt_decodeFilterOct", Module::SymbolKind::Function}, {"meshopt_decodeFilterQuat", Module::SymbolKind::Function}, {"meshopt_decodeFilterExp", Module::SymbolKind::Function}, {"sbrk", Module::SymbolKind::Function} };

std::shared_ptr<Module> createMeshopt__decoderModule() {
  return std::make_shared<WASMMeshopt__decoderModule>("meshopt_decoder");
}

const std::vector<Module::ImportInfo>& WASMMeshopt__decoderModule::getImports() const {
  return imports;
}

const std::vector<Module::ExportInfo>& WASMMeshopt__decoderModule::getExports() const {
  return exports;
}

void WASMMeshopt__decoderModule::createInstance(jsi::Runtime& rt, facebook::jsi::Object& target, jsi::Object&& importObject) const {
  return createMeshopt__decoderExports(rt, target, std::move(importObject));
}

}
