# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as builder

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install python3-pip  git

RUN apt update && apt install -y libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 libgbm-dev lsb-release xdg-utils wget

COPY package.json .
COPY packages/bot/package.json ./packages/bot/
COPY packages/engine/package.json ./packages/engine/
COPY packages/server-core/package.json ./packages/server-core/

RUN npm install --production=false --loglevel notice --legacy-peer-deps
RUN npm run install-test-e2e

# copy then compile the code
COPY . .

ENV APP_ENV=production

FROM node:16-buster-slim as runner
RUN apt update && apt install -y libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 libgbm-dev lsb-release xdg-utils wget
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/start-testbot.sh"]
