aws/
awscliv2.zip
.git/
*docker-compose*
node_modules
kubectl
lib/
packages/client/dist
**/*.test.ts
**/*.test.tsx
**/tests/
**/vendor/
packages/**/node_modules
package-lock.json
packages/**/package-lock.json
packages/projects/projects/*/*/public
packages/projects/projects/*/*/assets


kubernetes/**
.vscode
config/prod.json

.env
.env.local
.idea/
