# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install python3-pip

# Installs latest Chromium package.
RUN apk add --no-cache \
      chromium \
      nss \
      freetype \
      harfbuzz \
      ca-certificates \
      ttf-freefont

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    
COPY package.json .
COPY packages/bot/package.json ./packages/bot/
COPY packages/engine/package.json ./packages/engine/
COPY packages/server-core/package.json ./packages/server-core/

RUN npm install --production=false --loglevel notice --legacy-peer-deps
RUN npm run install-test-e2e

# copy then compile the code
COPY . .

ENV APP_ENV=production

CMD ["scripts/start-testbot.sh"]
