# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install python3-pip

RUN apt-get update

RUN apt-get install -y \
    fonts-liberation \
    gconf-service \
    libappindicator1 \
    libasound2 \
    libatk1.0-0 \
    libcairo2 \
    libcups2 \
    libfontconfig1 \
    libgbm-dev \
    libgdk-pixbuf2.0-0 \
    libgtk-3-0 \
    libicu-dev \
    libjpeg-dev \
    libnspr4 \
    libnss3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libpng-dev \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    xdg-utils
    
COPY package.json .
COPY packages/bot/package.json ./packages/bot/
COPY packages/engine/package.json ./packages/engine/
COPY packages/server-core/package.json ./packages/server-core/

RUN npm install --production=false --loglevel notice --legacy-peer-deps
RUN npm run install-test-e2e

# copy then compile the code
COPY . .

ENV APP_ENV=production

CMD ["scripts/start-testbot.sh"]
