enum EditorEvents {
  RENDER_MODE_CHANGED,
  PLAY_MODE_CHANGED,
  FLY_MODE_CHANGED,
  TRANSFROM_MODE_CHANGED,
  TRANSFORM_SPACE_CHANGED,
  TRANSFORM_PIVOT_CHANGED,
  SNAP_SETTINGS_CHANGED
}

export default EditorEvents
