enum EditorEvents {
  BEFORE_SELECTION_CHANGED,

  SCENE_GRAPH_CHANGED,
  OBJECTS_CHANGED,

  PROJECT_LOADED,
  RENDERER_INITIALIZED,

  FLY_MODE_CHANGED,
  TRANSFROM_MODE_CHANGED,
  TRANSFORM_PIVOT_CHANGED,
  SNAP_SETTINGS_CHANGED,

  ERROR
}

export default EditorEvents
