export const LOCATION_BAN_CREATED = 'LOCATION_BAN_CREATED';

export const SCENES_RETRIEVED = 'SCENES_RETRIEVED';
export const LOCATION_TYPES_RETRIEVED = 'LOCATION_TYPES_RETRIEVED';
export const SET_CURRENT_SCENE = 'SET_CURRENT_SCENE';

export const CLEAR_CHANNEL_LAYER_USERS = 'CLEAR_CHANNEL_LAYER_USERS';
export const LOADED_CHANNEL_LAYER_USERS = 'LOADED_CHANNEL_LAYER_USERS';
export const ADDED_CHANNEL_LAYER_USER = 'ADDED_CHANNEL_LAYER_USER';
export const REMOVED_CHANNEL_LAYER_USER = 'REMOVED_CHANNEL_LAYER_USER';

export const INSTANCE_CREATE = "INSTANCE_CREATE";
export const INSTANCE_REMOVED_ROW = "INSTANCE_REMOVED_ROW";
export const INSTANCE_PATCHED = "INSTANCE_PATCHED";