export const INSTANCE_SERVER_PROVISIONING = 'INSTANCE_SERVER_PROVISIONING';
export const INSTANCE_SERVER_PROVISIONED = 'INSTANCE_SERVER_PROVISIONED';
export const INSTANCE_SERVER_CONNECTING = 'INSTANCE_SERVER_CONNECTING';
export const INSTANCE_SERVER_CONNECTED = 'INSTANCE_SERVER_CONNECTED';
export const INSTANCE_SERVER_DISCONNECTED = 'INSTANCE_SERVER_DISCONNECTED';
export const SOCKET_CREATED = 'SOCKET_CREATED';

export const FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION';
export const LOCATIONS_RETRIEVED = 'LOCATIONS_RETRIEVED';
export const INSTANCES_RETRIEVED = 'INSTANCES_RETRIEVED';
export const LOCATION_RETRIEVED = 'LOCATION_RETRIEVED';
export const LOCATION_CREATED = 'LOCATION_CREATED';
export const LOCATION_PATCHED = 'LOCATION_PATCHED';
export const LOCATION_REMOVED = 'LOCATION_REMOVED';
export const LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND';

export const LOCATION_BAN_CREATED = 'LOCATION_BAN_CREATED';

export const SCENES_RETRIEVED = 'SCENES_RETRIEVED';
export const LOCATION_TYPES_RETRIEVED = 'LOCATION_TYPES_RETRIEVED';
export const SET_CURRENT_SCENE = 'SET_CURRENT_SCENE';

export const CHANNEL_SERVER_PROVISIONING = 'CHANNEL_SERVER_PROVISIONING';
export const CHANNEL_SERVER_PROVISIONED = 'CHANNEL_SERVER_PROVISIONED';
export const CHANNEL_SERVER_CONNECTING = 'CHANNEL_SERVER_CONNECTING';
export const CHANNEL_SERVER_CONNECTED = 'CHANNEL_SERVER_CONNECTED';
export const CHANNEL_SERVER_DISCONNECTED = 'CHANNEL_SERVER_DISCONNECTED';

export const CLEAR_CHANNEL_LAYER_USERS = 'CLEAR_CHANNEL_LAYER_USERS';
export const LOADED_CHANNEL_LAYER_USERS = 'LOADED_CHANNEL_LAYER_USERS';
export const ADDED_CHANNEL_LAYER_USER = 'ADDED_CHANNEL_LAYER_USER';
export const REMOVED_CHANNEL_LAYER_USER = 'REMOVED_CHANNEL_LAYER_USER';

export const INSTANCE_CREATE = "INSTANCE_CREATE";
export const INSTANCE_REMOVED_ROW = "INSTANCE_REMOVED_ROW";
export const INSTANCE_PATCHED = "INSTANCE_PATCHED";