export const LOCATION_TYPES_RETRIEVED = 'LOCATION_TYPES_RETRIEVED'
export const SET_CURRENT_SCENE = 'SET_CURRENT_SCENE'
export const SCENES_FETCHED_SUCCESS = 'SCENES_FETCHED_SUCCESS'
export const SCENES_FETCHED_ERROR = 'SCENES_FETCHED_ERROR'
export const REMOVE_SCENE = 'REMOVE_SCENE'

export const CLEAR_CHANNEL_LAYER_USERS = 'CLEAR_CHANNEL_LAYER_USERS'
export const LOADED_CHANNEL_LAYER_USERS = 'LOADED_CHANNEL_LAYER_USERS'
export const ADDED_CHANNEL_LAYER_USER = 'ADDED_CHANNEL_LAYER_USER'
export const REMOVED_CHANNEL_LAYER_USER = 'REMOVED_CHANNEL_LAYER_USER'

export const INSTANCES_RETRIEVED = 'INSTANCES_RETRIEVED'
export const INSTANCE_REMOVED_ROW = 'INSTANCE_REMOVED_ROW'
export const INSTANCE_PATCHED = 'INSTANCE_PATCHED'

export const USER_ROLE_RETRIEVED = 'USER_ROLE_RETRIEVED'
export const USER_ROLE_CREATED = 'USER_ROLE_CREATED'
export const USER_ROLE_UPDATED = 'USER_ROLE_UPDATED'
