export interface StaticResourceInterface {
  id: string
  sid: string
  url: string
  key: string
  hash?: string
  mimeType: string
  metadata: any
  project?: string
  driver?: string
  attribution?: string
  licensing?: string
  tags?: string[]
  originalURL?: string[]
  LOD0_url: string
  LOD0_metadata: object
  LOD1_url?: string
  LOD1_metadata?: object
  LOD2_url?: string
  LOD2_metadata?: object
  LOD3_url?: string
  LOD3_metadata?: object
  LOD4_url?: string
  LOD4_metadata?: object
  LOD5_url?: string
  LOD5_metadata?: object
  LOD6_url?: string
  LOD6_metadata?: object
  LOD7_url?: string
  LOD7_metadata?: object
  LOD8_url?: string
  LOD8_metadata?: object
  LOD9_url?: string
  LOD9_metadata?: object
  LOD10_url?: string
  LOD10_metadata?: object
  LOD11_url?: string
  LOD11_metadata?: object
  LOD12_url?: string
  LOD12_metadata?: object
  LOD13_url?: string
  LOD13_metadata?: object
  LOD14_url?: string
  LOD14_metadata?: object
  LOD15_url?: string
  LOD15_metadata?: object
  LOD16_url?: string
  LOD16_metadata?: object
  LOD17_url?: string
  LOD17_metadata?: object
}
