export const DEFAULT_AVATARS = ['Sonny', 'Razer1', 'Razer2', 'Razer3', 'Razer4', 'Razer5', 'Razer6'] // 'Allison', , 'Rose', 'Andy', 'Erik', 'Geoff', 'Jace', 'Karthik'
export const DEFAULT_AVATAR_ID = 'Razer1'
export const AVATAR_FILE_ALLOWED_EXTENSIONS = '.glb,.gltf,.vrm,.fbx'
export const MIN_AVATAR_FILE_SIZE = 0
export const MAX_AVATAR_FILE_SIZE = 15728640 // 15 MB
export const MIN_THUMBNAIL_FILE_SIZE = 0
export const MAX_THUMBNAIL_FILE_SIZE = 2097152 // 2 MB
export const PRESIGNED_URL_EXPIRATION_DURATION = 3600 // 1 hour
export const THUMBNAIL_FILE_ALLOWED_EXTENSIONS = '.png,.jpg'
export const THUMBNAIL_WIDTH = 300
export const THUMBNAIL_HEIGHT = 300
export const MAX_ALLOWED_TRIANGLES = 100000
