# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster

RUN apt update
RUN apt-get install build-essential meson python3-testresources python3-venv python3-pip -y
# Create app directory
WORKDIR /app

RUN npm install -g lerna cross-env rimraf ts-eager --loglevel notice

# to make use of caching, copy only package files and install dependencies
COPY package.json .
COPY packages/common/package.json ./packages/common/
COPY packages/engine/package.json ./packages/engine/
COPY packages/gameserver/package.json ./packages/gameserver/
COPY packages/matchmaking/package.json ./packages/matchmaking/
COPY packages/projects/package.json ./packages/projects/
COPY packages/server-core/package.json ./packages/server-core/

RUN npm install --production=false --loglevel notice --legacy-peer-deps

COPY . .

# copy then compile the code

ENV APP_ENV=production

CMD ["scripts/start-server.sh"]
