# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as builder

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install python3-pip

COPY package.json .
COPY packages/client/package.json ./packages/client/
COPY packages/client-core/package.json ./packages/client-core/
COPY packages/common/package.json ./packages/common/
COPY packages/editor/package.json ./packages/editor/
COPY packages/engine/package.json ./packages/engine/
COPY packages/projects/package.json ./packages/projects/
COPY packages/server-core/package.json ./packages/server-core/
COPY project-package-jsons ./

RUN npm install --production=false --loglevel notice --legacy-peer-deps

# copy then compile the code
COPY . .

ARG MYSQL_HOST
ARG MYSQL_USER
ARG MYSQL_PORT
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER

RUN npm run build-client

ENV APP_ENV=production

FROM node:16-buster-slim as runner
WORKDIR /app

COPY --from=builder /app/packages/client ./packages/client
COPY --from=builder /app/scripts ./scripts

RUN npm install express app-root-path

CMD ["scripts/start-server.sh"]
