export const VIDEO_CREATED = 'VIDEO_CREATED';
export const VIDEO_UPDATED = 'VIDEO_UPDATED';
export const VIDEO_DELETED = 'VIDEO_DELETED';

export const CONTENT_PACK_CREATED = 'CONTENT_PACK_CREATED';
export const CONTENT_PACK_PATCHED = 'CONTENT_PACK_PATCHED';
export const LOADED_CONTENT_PACKS = 'LOADED_CONTENT_PACKS';

export const PARTY_ADMIN_CREATED = 'PARTY_ADMIN_CREATED';
export const PARTY_ADMIN_DISPLAYED = 'PARTY_ADMIN_DISPLAYED';
export const USER_ADMIN_REMOVED = "USER_ADMIN_REMOVED";
export const USER_ADMIN_CREATED = "USER_ADMIN_CREATED";
export const USER_ADMIN_PATCHED = "USER_ADMIN_PATCHED";
export const USER_SEARCH_ADMIN = "USER_SEARCH_ADMIN";
export const SINGLE_USER_ADMIN_LOADED = "SINGLE_USER_ADMIN_LOADED";
export const USER_ROLE_RETRIEVED = "USER_ROLE_RETRIEVED";
export const USER_ROLE_CREATED = "USER_ROLE_CREATED";
export const USER_ROLE_UPDATED = "USER_ROLE_UPDATED";
export const LOADED_USERS = "LOADED_USERS";