export const VIDEO_CREATED = 'VIDEO_CREATED'
export const VIDEO_UPDATED = 'VIDEO_UPDATED'
export const VIDEO_DELETED = 'VIDEO_DELETED'

export const CONTENT_PACK_CREATED = 'CONTENT_PACK_CREATED'
export const CONTENT_PACK_PATCHED = 'CONTENT_PACK_PATCHED'
export const LOADED_CONTENT_PACKS = 'LOADED_CONTENT_PACKS'

export const PARTY_ADMIN_CREATED = 'PARTY_ADMIN_CREATED'
export const PARTY_ADMIN_DISPLAYED = 'PARTY_ADMIN_DISPLAYED'
export const USER_ADMIN_REMOVED = 'USER_ADMIN_REMOVED'
export const USER_ADMIN_CREATED = 'USER_ADMIN_CREATED'
export const USER_ADMIN_PATCHED = 'USER_ADMIN_PATCHED'
export const USER_SEARCH_ADMIN = 'USER_SEARCH_ADMIN'
export const SINGLE_USER_ADMIN_LOADED = 'SINGLE_USER_ADMIN_LOADED'
// export const USER_ROLE_RETRIEVED = "USER_ROLE_RETRIEVED";
// export const USER_ROLE_CREATED = "USER_ROLE_CREATED";
// export const USER_ROLE_UPDATED = "USER_ROLE_UPDATED";
export const ADMIN_LOADED_USERS = 'LOADED_USERS'

export const ADMIN_INSTANCES_RETRIEVED = 'INSTANCES_RETRIEVED'
export const ADMIN_INSTANCE_CREATE = 'INSTANCE_CREATE'
export const ADMIN_INSTANCE_PATCHED = 'INSTANCE_PATCHED'
export const ADMIN_INSTANCE_REMOVED_ROW = 'INSTANCE_REMOVED_ROW'

export const ADMIN_LOCATION_TYPES_RETRIEVED = 'LOCATION_TYPES_RETRIEVED'
export const ADMIN_LOCATIONS_RETRIEVED = 'LOCATIONS_RETRIEVED'
export const ADMIN_LOCATION_CREATED = 'LOCATION_CREATED'
export const ADMIN_LOCATION_PATCHED = 'LOCATION_PATCHED'
export const ADMIN_LOCATION_REMOVED = 'LOCATION_REMOVED'
export const ADMIN_FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION'
export const ADMIN_LOCATION_RETRIEVED = 'LOCATION_RETRIEVED'
export const ADMIN_LOCATION_BAN_CREATED = 'LOCATION_BAN_CREATED'
export const ADMIN_LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND'

export const BOT_ADMIN_CREATE = 'BOT_ADMIN_CREATE'
export const BOT_ADMIN_DISPLAY = 'BOT_ADMIN_DISPLAY'
export const BOT_COMMAND_ADMIN_CREATE = 'BOT_COMMAND_ADMIN_CREATE'
export const BOT_ADMIN_REMOVE = 'BOT_ADMIN_REMOVE'
export const BOT_COMMAND_ADMIN_REMOVE = 'BOT_COMMAND_ADMIN_REMOVE'
export const BOT_ADMIN_UPDATE = 'BOT_ADMIN_UPDATE'

export const STATIC_RESOURCE_RETRIEVED = 'STATIC_RESOURCE_RETRIEVED'

export const ADMIN_FETCH_AR_MEDIA = 'ADMIN_FETCH_AR_MEDIA'
export const UPDATE_AR_MEDIA = 'UPDATE_AR_MEDIA'
export const ADD_ARMEDIA = 'ADD_ARMEDIA'
export const ARMEDIA_ADMIN_RETRIEVED = 'ARMEDIA_ADMIN_RETRIEVED'
export const REMOVE_ARMEDIA = 'REMOVE_ARMEDIA'
export const ARMEDIA_FETCHING = 'ARMEDIA_FETCHING'

export const FEEDS_ADMIN_RETRIEVED = 'FEEDS_ADMIN_RETRIEVED'
export const REMOVE_FEED = 'REMOVE_FEED'
export const ADMIN_FEEDS_FETCH = 'ADMIN_FEEDS_FETCH'
export const ADD_AS_ADMIN_FEED = 'ADD_AS_ADMIN_FEED'
export const RETRIEVE_CREATOR_AS_ADMIN = 'RETRIEVE_CREATOR_AS_ADMIN'
export const CREATE_CREATOR_AS_ADMIN = 'CREATE_CREATOR_AS_ADMIN'
