export const VIDEO_CREATED = 'VIDEO_CREATED';
export const VIDEO_UPDATED = 'VIDEO_UPDATED';
export const VIDEO_DELETED = 'VIDEO_DELETED';

export const CONTENT_PACK_CREATED = 'CONTENT_PACK_CREATED';
export const CONTENT_PACK_PATCHED = 'CONTENT_PACK_PATCHED';
export const LOADED_CONTENT_PACKS = 'LOADED_CONTENT_PACKS';

export const PARTY_ADMIN_CREATED = 'PARTY_ADMIN_CREATED';
export const PARTY_ADMIN_DISPLAYED = 'PARTY_ADMIN_DISPLAYED';
export const USER_ADMIN_REMOVED = "USER_ADMIN_REMOVED";
export const USER_ADMIN_CREATED = "USER_ADMIN_CREATED";
export const USER_ADMIN_PATCHED = "USER_ADMIN_PATCHED";
export const USER_SEARCH_ADMIN = "USER_SEARCH_ADMIN";
export const SINGLE_USER_ADMIN_LOADED = "SINGLE_USER_ADMIN_LOADED";
export const USER_ROLE_RETRIEVED = "USER_ROLE_RETRIEVED";
export const USER_ROLE_CREATED = "USER_ROLE_CREATED";
export const USER_ROLE_UPDATED = "USER_ROLE_UPDATED";
export const LOADED_USERS = "LOADED_USERS";

export const INSTANCES_RETRIEVED = "INSTANCES_RETRIEVED";
export const INSTANCE_CREATE = "INSTANCE_CREATE";
export const INSTANCE_PATCHED = "INSTANCE_PATCHED";
export const INSTANCE_REMOVED_ROW = "INSTANCE_REMOVED_ROW";

export const LOCATION_TYPES_RETRIEVED= "LOCATION_TYPES_RETRIEVED";
export const LOCATIONS_RETRIEVED = "LOCATIONS_RETRIEVED";
export const LOCATION_CREATED = "LOCATION_CREATED";
export const LOCATION_PATCHED = "LOCATION_PATCHED";
export const LOCATION_REMOVED = "LOCATION_REMOVED";
export const FETCH_CURRENT_LOCATION = "FETCH_CURRENT_LOCATION";
export const LOCATION_RETRIEVED = "LOCATION_RETRIEVED";
export const LOCATION_BAN_CREATED = "LOCATION_BAN_CREATED";
export const LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND";

export const BOT_ADMIN_CREATE = "BOT_ADMIN_CREATE";
export const BOT_ADMIN_DISPLAY = "BOT_ADMIN_DISPLAY";
export const BOT_COMMAND_ADMIN_CREATE = "BOT_COMMAND_ADMIN_CREATE";
export const BOT_ADMIN_REMOVE = "BOT_ADMIN_REMOVE";
export const BOT_COMMAND_ADMIN_REMOVE = "BOT_COMMAND_ADMIN_REMOVE";