export const LOADED_FRIENDS = 'LOADED_FRIENDS'
export const CREATED_FRIEND = 'CREATED_FRIEND'
export const PATCHED_FRIEND = 'PATCHED_FRIEND'
export const REMOVED_FRIEND = 'REMOVED_FRIEND'
export const FETCHING_FRIENDS = 'FETCHING_FRIENDS'

export const INVITE_SENT = 'INVITE_SENT'
export const SENT_INVITES_RETRIEVED = 'SENT_INVITES_RETRIEVED'
export const RECEIVED_INVITES_RETRIEVED = 'RECEIVED_INVITES_RECEIVED'
export const CREATED_RECEIVED_INVITE = 'CREATED_RECEIVED_INVITE'
export const REMOVED_RECEIVED_INVITE = 'REMOVED_RECEIVED_INVITE'
export const CREATED_SENT_INVITE = 'CREATED_SENT_INVITE'
export const REMOVED_SENT_INVITE = 'REMOVED_SENT_INVITE'
export const ACCEPTED_INVITE = 'ACCEPTED_INVITE'
export const DECLINED_INVITE = 'DECLINED_INVITE'
export const INVITE_TARGET_SET = 'INVITE_TARGET_SET'
export const FETCHING_SENT_INVITES = 'FETCHING_SENT_INVITES'
export const FETCHING_RECEIVED_INVITES = 'FETCHING_RECEIVED_INVITES'

export const LOADED_GROUPS = 'LOADED_GROUPS'
export const CREATED_GROUP = 'CREATED_GROUP'
export const PATCHED_GROUP = 'PATCHED_GROUP'
export const REMOVED_GROUP = 'REMOVED_GROUP'
export const CREATED_GROUP_USER = 'CREATED_GROUP_USER'
export const PATCHED_GROUP_USER = 'PATCHED_GROUP_USER'
export const INVITED_GROUP_USER = 'INVITED_GROUP_USER'
export const REMOVED_GROUP_USER = 'REMOVED_GROUP_USER'
export const LEFT_GROUP = 'LEFT_GROUP'
export const FETCHING_GROUPS = 'FETCHING_GROUPS'
export const LOADED_INVITABLE_GROUPS = 'LOADED_INVITABLE_GROUPS'
export const FETCHING_INVITABLE_GROUPS = 'FETCHING_INVITABLE_GROUPS'

export const LOADED_PARTY = 'LOADED_PARTY'
export const CREATED_PARTY = 'CREATED_PARTY'
export const PATCHED_PARTY = 'PATCHED_PARTY'
export const REMOVED_PARTY = 'REMOVED_PARTY'
export const CREATED_PARTY_USER = 'CREATED_PARTY_USER'
export const PATCHED_PARTY_USER = 'PATCHED_PARTY_USER'
export const INVITED_PARTY_USER = 'INVITED_PARTY_USER'
export const REMOVED_PARTY_USER = 'REMOVED_PARTY_USER'
export const LEFT_PARTY = 'LEFT_PARTY'

export const CHAT_TARGET_SET = 'CHAT_TARGET_SET'
export const FETCHING_INSTANCE_CHANNEL = 'FETCHING_INSTANCE_CHANNEL'
export const LOADED_CHANNEL = 'LOADED_CHANNEL'
export const LOADED_CHANNELS = 'LOADED_CHANNELS'
export const CREATED_CHANNEL = 'CREATED_CHANNEL'
export const PATCHED_CHANNEL = 'PATCHED_CHANNEL'
export const REMOVED_CHANNEL = 'REMOVED_CHANNEL'
export const CREATED_MESSAGE = 'CREATED_MESSAGE'
export const LOADED_MESSAGES = 'LOADED_MESSAGES'
export const PATCHED_MESSAGE = 'PATCHED_MESSAGE'
export const REMOVED_MESSAGE = 'REMOVED_MESSAGE'
export const SET_MESSAGE_SCROLL_INIT = 'SET_MESSAGE_SCROLL_INIT'

export const INVITE_TYPE_CREATE = 'INVITE_TYPE_CREATE'
export const LOAD_INVITE_TYPE = 'LOAD_INVITE_TYPE'
export const REMOVED_INVITE_TYPE = 'REMOVED_INVITE_TYPE'
export const FETCHING_RECEIVED_INVITES_TYPES = 'FETCHING_RECEIVED_INVITES_TYPES'

export const FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION'
export const LOCATIONS_RETRIEVED = 'LOCATIONS_RETRIEVED'
export const LOCATION_RETRIEVED = 'LOCATION_RETRIEVED'
export const LOCATION_CREATED = 'LOCATION_CREATED'
export const LOCATION_PATCHED = 'LOCATION_PATCHED'
export const LOCATION_REMOVED = 'LOCATION_REMOVED'
export const LOCATION_BAN_CREATED = 'LOCATION_BAN_CREATED'
export const LOCATION_NOT_FOUND = 'LOCATION_NOT_FOUND'

export const ADD_ARMEDIA = 'ADD_ARMEDIA'

export const ADD_FEED = 'ADD_FEED'
export const ADD_FEED_BOOKMARK = 'ADD_FEED_BOOKMARK'
export const ADD_FEED_COMMENT = 'ADD_FEED_COMMENT'
export const ADD_FEED_COMMENT_FIRES = 'ADD_FEED_COMMENT_FIRES'
export const ADD_FEED_FEATURED = 'ADD_FEED_FEATURED'
export const ADD_FEED_FIRES = 'ADD_FEED_FIRES'
export const ADD_FEED_LIKES = 'ADD_FEED_LIKES'
export const ADD_FEED_REPORT = 'ADD_FEED_REPORT'
export const ADD_FEED_VIEW = 'ADD_FEED_VIEW'

export const ADMIN_FEEDS_FETCH = 'ADMIN_FEEDS_FETCH'

export const ARMEDIA_ADMIN_RETRIEVED = 'ARMEDIA_ADMIN_RETRIEVED'
export const ARMEDIA_FETCHING = 'ARMEDIA_FETCHING'
export const ARMEDIA_FETCHING_ITEM = 'ARMEDIA_FETCHING_ITEM'
export const ARMEDIA_RETRIEVED = 'ARMEDIA_RETRIEVED'
export const ARMEDIA_RETRIEVED_ITEM = 'ARMEDIA_RETRIEVED_ITEM'

export const BOOKMARK_FEEDS_FETCH = 'BOOKMARK_FEEDS_FETCH'

export const CHANGE_ARMEDIA_CHOOSE_STATE = 'CHANGE_ARMEDIA_CHOOSE_STATE'
export const CHANGE_CREATOR_FORM_STATE = 'CHANGE_CREATOR_FORM_STATE'
export const CHANGE_CREATOR_PAGE_STATE = 'CHANGE_CREATOR_PAGE_STATE'
export const CHANGE_FEED_PAGE_STATE = 'CHANGE_FEED_PAGE_STATE'
export const CHANGE_NEW_FEED_PAGE_STATE = 'CHANGE_NEW_FEED_PAGE_STATE'
export const CHANGE_SHARE_FORM_STATE = 'CHANGE_SHARE_FORM_STATE'
export const CHANGE_WEB_XR_STATE = 'CHANGE_WEB_XR_STATE'

export const CLEAR_CREATOR_FEATURED = 'CLEAR_CREATOR_FEATURED'

export const COMMENT_FIRES = 'COMMENT_FIRES'

export const CREATOR_BLOCKED_RETRIEVED = 'CREATOR_BLOCKED_RETRIEVED'
export const CREATOR_FEEDS_FETCH = 'CREATOR_FEEDS_FETCH'
export const CREATOR_FETCH = 'CREATOR_FETCH'
export const CREATOR_FOLLOWERS_RETRIEVED = 'CREATOR_FOLLOWERS_RETRIEVED'
export const CREATOR_FOLLOWING_RETRIEVED = 'CREATOR_FOLLOWING_RETRIEVED'
export const CREATOR_NOTIFICATION_LIST_RETRIEVED = 'CREATOR_NOTIFICATION_LIST_RETRIEVED'
export const CREATOR_RETRIEVED = 'CREATOR_RETRIEVED'

export const CREATORS_FETCH = 'CREATORS_FETCH'
export const CREATORS_RETRIEVED = 'CREATORS_RETRIEVED'

export const CURRENT_CREATOR_FETCH = 'CURRENT_CREATOR_FETCH'
export const CURRENT_CREATOR_RETRIEVED = 'CURRENT_CREATOR_RETRIEVED'

export const DELETE_FEED = 'DELETE_FEED'

export const FEATURED_FEEDS_FETCH = 'FEATURED_FEEDS_FETCH'

export const FEED_COMMENTS_FETCH = 'FEED_COMMENTS_FETCH'
export const FEED_COMMENTS_RETRIEVED = 'FEED_COMMENTS_RETRIEVED'

export const FEED_FIRES_FETCH = 'FEEDFIRES_FETCH'
export const FEED_FIRES_RETRIEVED = 'FEED_FIRES_RETRIEVED'
export const FEED_LIKES_FETCH = 'FEEDLIKES_FETCH'
export const FEED_LIKES_RETRIEVED = 'FEED_LIKES_RETRIEVED'

export const FEED_RETRIEVED = 'FEED_RETRIEVED'

export const FEEDS_AS_ADMIN_RETRIEVED = 'FEEDS_AS_ADMIN_RETRIEVED'
export const FEEDS_BOOKMARK_RETRIEVED = 'FEEDS_BOOKMARK_RETRIEVED'
export const FEEDS_CREATOR_RETRIEVED = 'FEEDS_CREATOR_RETRIEVED'
export const FEEDS_FEATURED_RETRIEVED = 'FEEDS_FEATURED_RETRIEVED'
export const FEEDS_FETCH = 'FEEDS_FETCH'
export const FEEDS_FIRED_RETRIEVED = 'FEEDS_FIRED_RETRIEVED'
export const FEEDS_MY_FEATURED_RETRIEVED = 'FEEDS_MY_FEATURED_RETRIEVED'
export const FEEDS_RETRIEVED = 'FEEDS_RETRIEVED'

export const FIRED_FEEDS_FETCH = 'FIRED_FEEDS_FETCH'

export const LAST_FEED_VIDEO_URL = 'LAST_FEED_VIDEO_URL'

export const MY_FEATURED_FEEDS_FETCH = 'MY_FEATURED_FEEDS_FETCH'

export const REMOVE_ARMEDIA = 'REMOVE_ARMEDIA'

export const REMOVE_FEED_BOOKMARK = 'REMOVE_FEED_BOOKMARK'
export const REMOVE_FEED_COMMENT_FIRES = 'REMOVE_FEED_COMMENT_FIRES'
export const REMOVE_FEED_FEATURED = 'REMOVE_FEED_FEATURED'
export const REMOVE_FEED_FIRES = 'REMOVE_FEED_FIRES'
export const REMOVE_FEED_LIKES = 'REMOVE_FEED_LIKES'

export const SET_CREATOR_AS_BLOCKED = 'SET_CREATOR_AS_BLOCKED'
export const SET_CREATOR_AS_FOLLOWED = 'SET_CREATOR_AS_FOLLOWED'
export const SET_CREATOR_AS_UN_BLOCKED = 'SET_CREATOR_AS_UN_BLOCKED'
export const SET_CREATOR_NOT_FOLLOWED = 'SET_CREATOR_NOT_FOLLOWED'

export const SET_STATE_CREATORS = 'SET_STATE_CREATORS'

export const THEFEEDS_FIRES_FETCH = 'THEFEEDS_FIRES_FETCH'
export const THEFEEDS_FIRES_RETRIEVED = 'THEFEEDS_FIRES_RETRIEVED'

export const UPDATE_AR_MEDIA = 'UPDATE_AR_MEDIA'

export const UPDATE_FEED = 'UPDATE_FEED'
