// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Attribution = sequelize.define('attribution', {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    creator: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    url: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'attribution',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Attribution.associate = (models) => {
    Attribution.belongsTo(models.license, {
      foreignKey: {
        name: 'licenseNameKey',
        field: 'licenseName',
      },
      targetKey: 'name',
      as: 'licenseName',
    });
    Attribution.belongsTo(models.staticResource, {
      foreignKey: {
        name: 'staticResourceIdKey',
        field: 'staticResourceId',
      },
      as: 'staticResource',
    });
    Attribution.belongsTo(models.collection, {
      foreignKey: {
        name: 'collectionIdKey',
        field: 'collectionId',
      },
      as: 'collection',
    });
  };

  return Attribution;
};
