// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const CollectionTag = sequelize.define('collectionTag', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
    collectionId: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    tagTag: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'collection_tag',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  CollectionTag.associate = (models) => {
    CollectionTag.belongsTo(models.collection, {
      foreignKey: {
        name: 'collectionIdKey',
        field: 'collectionId',
      },
      as: 'collection',
    });
    CollectionTag.belongsTo(models.tag, {
      foreignKey: {
        name: 'tagTagKey',
        field: 'tagTag',
      },
      targetKey: 'tag',
      as: 'linkedTagTag',
    });
  };

  return CollectionTag;
};
