// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const GroupUser = sequelize.define('groupUser', {
    id: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'group_user',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  GroupUser.associate = (models) => {
    GroupUser.belongsTo(models.group, {
      foreignKey: {
        name: 'groupIdKey',
        field: 'groupId',
      },
      as: 'group',
    });
    GroupUser.belongsTo(models.groupUserRank, {
      foreignKey: {
        name: 'groupUserRankKey',
        field: 'groupUserRank',
      },
      targetKey: 'rank',
      as: 'groupUserRank',
    });
    GroupUser.belongsTo(models.user, {
      foreignKey: {
        name: 'userIdKey',
        field: 'userId',
      },
      as: 'user',
    });
  };

  return GroupUser;
};
