// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Seat = sequelize.define('seat', {
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'seat',
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Seat.associate = (models) => {
    Seat.belongsTo(models.seatStatus, {
      foreignKey: {
        name: 'seatStatusKey',
        field: 'seatStatus',
      },
      targetKey: 'status',
      as: 'seatStatus',
    });
    Seat.belongsTo(models.user, {
      foreignKey: {
        name: 'userIdKey',
        field: 'userId',
      },
      as: 'user',
    });
    Seat.belongsTo(models.subscription, {
      foreignKey: {
        name: 'subscriptionIdKey',
        field: 'subscriptionId',
      },
      as: 'subscription',
    });
  };

  return Seat;
};
