// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const SeatStatus = sequelize.define('seatStatus', {
    status: {
      type: DataTypes.STRING,
      primaryKey: true,
      allowNull: false,
    },
  }, {
    tableName: 'seat_status',
    timestamps: false,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  SeatStatus.associate = (models) => {
    SeatStatus.hasMany(models.seat, {
      foreignKey: {
        name: 'seatStatusKey',
        field: 'seatStatus',
      },
      sourceKey: 'status',
      as: 'seatStatusSeats',
    });
  };

  return SeatStatus;
};
