#!/bin/bash
set -e
set -x

STAGE=$1
LABEL=$2
PACKAGE=$3
START_TIME=$4
PRIVATE_ECR=$5
REGION=$6

DOCKER_BUILDKIT=1 docker build -t $LABEL-$PACKAGE -f dockerfiles/$PACKAGE/Dockerfile-$PACKAGE \
  --build-arg MYSQL_HOST=$MYSQL_HOST \
  --build-arg MYSQL_PORT=$MYSQL_PORT \
  --build-arg MYSQL_PASSWORD=$MYSQL_PASSWORD \
  --build-arg MYSQL_USER=$MYSQL_USER \
  --build-arg MYSQL_DATABASE=$MYSQL_DATABASE \
  --build-arg VITE_CLIENT_HOST=$VITE_CLIENT_HOST \
  --build-arg VITE_SERVER_HOST=$VITE_SERVER_HOST \
  --build-arg VITE_MEDIATOR_SERVER=$VITE_MEDIATOR_SERVER \
  --build-arg VITE_GAMESERVER_HOST=$VITE_GAMESERVER_HOST \
  --build-arg VITE_APP_MAINNET_HOST_URL=$VITE_APP_MAINNET_HOST_URL \
  --build-arg VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_NFT_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_NFT_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_LEDGER_CANISTER_PRINCIPAL_ID=$VITE_APP_MAINNET_LEDGER_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_MAINNET_LEDGER_CANISTER_ACCOUNT_ID=$VITE_APP_MAINNET_LEDGER_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_MAINNET_USER_PRINCIPAL_ID=$VITE_APP_MAINNET_USER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_HOST_URL=$VITE_APP_LOCAL_HOST_URL \
  --build-arg VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_NFT_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_NFT_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_LEDGER_CANISTER_PRINCIPAL_ID=$VITE_APP_LOCAL_LEDGER_CANISTER_PRINCIPAL_ID \
  --build-arg VITE_APP_LOCAL_LEDGER_CANISTER_ACCOUNT_ID=$VITE_APP_LOCAL_LEDGER_CANISTER_ACCOUNT_ID \
  --build-arg VITE_APP_LOCAL_USER_PRINCIPAL_ID=$VITE_APP_LOCAL_USER_PRINCIPAL_ID .
bash ./scripts/publish_ecr.sh $RELEASE_NAME ${TAG}__${START_TIME} $DOCKER_LABEL $PACKAGE $PRIVATE_ECR $AWS_REGION
