
services:
  db:
    image: mariadb:10.7
    container_name: ir-engine_db
    environment:
      MYSQL_ROOT_PASSWORD: ir-engine-root
      MYSQL_DATABASE: ir-engine
      MYSQL_USER: server
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
  redis:
    image: redis
    container_name: ir-engine_redis
    command: redis-server
    ports:
      - '6379:6379'