services:
  minio:
    image: docker.io/bitnami/minio:latest
    container_name: ir-engine_minio_s3
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
      - ../certs/minio:/certs
    environment:
      MINIO_ROOT_USER: server
      MINIO_ROOT_PASSWORD: password
      MINIO_API_REQUESTS_MAX: 2000
      MINIO_API_REQUESTS_DEADLINE: 3m
      BITNAMI_DEBUG: 'true'
      MINIO_SCHEME: https
      MINIO_SKIP_CLIENT: 'yes'
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/minio/health/ready", "--insecure"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  init-buckets:
    image: docker.io/bitnami/minio-client:latest
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init-buckets.sh:/usr/local/bin/init-buckets.sh
    environment:
      MINIO_SERVER: https://minio:9000
      MINIO_ROOT_USER: server
      MINIO_ROOT_PASSWORD: password
    entrypoint: ["/bin/bash", "-c", "chmod +x /usr/local/bin/init-buckets.sh && /usr/local/bin/init-buckets.sh"]

volumes:
  minio_data:
    driver: local
