/*
CPAL-1.0 License

The contents of this file are subject to the Common Public Attribution License
Version 1.0. (the "License"); you may not use this file except in compliance
with the License. You may obtain a copy of the License at
https://github.com/ir-engine/ir-engine/blob/dev/LICENSE.
The License is based on the Mozilla Public License Version 1.1, but Sections 14
and 15 have been added to cover use of software over a computer network and 
provide for limited attribution for the Original Developer. In addition, 
Exhibit A has been modified to be consistent with Exhibit B.

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
specific language governing rights and limitations under the License.

The Original Code is Infinite Reality Engine.

The Original Developer is the Initial Developer. The Initial Developer of the
Original Code is the Infinite Reality Engine team.

All portions of the code written by the Infinite Reality Engine team are Copyright © 2021-2023 
Infinite Reality Engine. All Rights Reserved.
*/

import {
  SystemDefinitions,
  UUIDComponent,
  UndefinedEntity,
  createEngine,
  createEntity,
  destroyEngine,
  getComponent,
  removeEntity,
  setComponent
} from '@ir-engine/ecs'
import assert from 'assert'
import { Vector3 } from 'three'
import { mockSpatialEngine } from '../../tests/util/mockSpatialEngine'
import { SceneComponent } from '../renderer/components/SceneComponents'
import { EntityTreeComponent } from '../transform/components/EntityTree'
import { TransformComponent } from '../transform/components/TransformComponent'
import { TransformSystem } from '../transform/systems/TransformSystem'
import { PhysicsPreTransformSystem, PhysicsSystem } from './PhysicsModule'
import { Physics, PhysicsWorld } from './classes/Physics'
import { ColliderComponent } from './components/ColliderComponent'
import { RigidBodyComponent } from './components/RigidBodyComponent'
import { BodyTypes } from './types/PhysicsTypes'

/*
# Physics : Integration
We have a few situations:
- manipulating `rigidbodies` & `collider` transform hierarchies in the studio
  specifically, nested/complex entity hierarchies
- multi-scene coordinate space support    (demos are in the dev test suite)
  - XR locomotion demo
  - scene placement demo
  - multiple scenes demo
- physics based dynamic object movement & inter-physics frame transform interpolation

## Integration Test
Integration testing is defined as testing the result of multiple modules.
For the physics, the modules would be:
- `RigidbodyComponent`
- `ColliderComponent`
- `TransformComponent`
- `PhysicsSystem`
- `PhysicsPreTransformSystem`
- `TransformSystem`
We'd be asserting between system executes once the components are set up correctly

All it needs to be is:
- What you've added for PhysicsSystem.test.ts with physicsSystemExecute()
- but for the three systems mentioned above, all in the same test

Systems Execution Order
1. InputSystemGroup         // executeSystem
2. SimulationSystemGroup    // executeFixedSystem
3. AnimationSystemGroup     // executeSystem
4. PresentationSystemGroup  // executeSystem
*/

describe('Integration : PhysicsSystem + PhysicsPreTransformSystem + TransformSystem', () => {
  const execute = {
    physicsSystem: SystemDefinitions.get(PhysicsSystem)!.execute, // with: SimulationSystemGroup
    physicsPreTransformSystem: SystemDefinitions.get(PhysicsPreTransformSystem)!.execute, // after: TransformDirtyUpdateSystem -> before: TransformSystem
    transformSystem: SystemDefinitions.get(TransformSystem)!.execute // after: AnimationSystemGroup
  }

  describe('Category 1 ', () => {
    let testEntity = UndefinedEntity
    let physicsWorldEntity = UndefinedEntity
    let physicsWorld: PhysicsWorld

    beforeEach(async () => {
      createEngine()
      mockSpatialEngine()
      await Physics.load()
      physicsWorldEntity = createEntity()
      setComponent(physicsWorldEntity, UUIDComponent, UUIDComponent.generateUUID())
      setComponent(physicsWorldEntity, EntityTreeComponent)
      setComponent(physicsWorldEntity, SceneComponent)
      setComponent(physicsWorldEntity, TransformComponent)
      physicsWorld = Physics.createWorld(getComponent(physicsWorldEntity, UUIDComponent))
      physicsWorld.timestep = 1 / 60

      testEntity = createEntity()
    })

    afterEach(() => {
      removeEntity(testEntity)
      removeEntity(physicsWorldEntity)
      return destroyEngine()
    })

    type ResultData = Vector3
    type ResultEntry = {
      physicsSystem: ResultData
      physicsPreTransformSystem: ResultData
      transformSystem: ResultData
    }
    type Result = {
      before: ResultEntry
      after: ResultEntry
    }

    it.skip("should commit pose modifications generated by the Physics into the entity's TransformComponent data", () => {
      const testImpulse = new Vector3(1, 2, 3)
      // Set the data as expected
      setComponent(testEntity, EntityTreeComponent, { parentEntity: physicsWorldEntity })
      setComponent(testEntity, TransformComponent)
      setComponent(testEntity, RigidBodyComponent, { type: BodyTypes.Dynamic })
      setComponent(testEntity, ColliderComponent)
      const Expected: Result = {
        before: {
          physicsSystem: getComponent(testEntity, TransformComponent).position.clone(),
          physicsPreTransformSystem: getComponent(testEntity, TransformComponent).position.clone(),
          transformSystem: getComponent(testEntity, TransformComponent).position.clone()
        },
        after: {
          physicsSystem: getComponent(testEntity, TransformComponent).position.clone(),
          physicsPreTransformSystem: getComponent(testEntity, TransformComponent).position.clone(),
          transformSystem: new Vector3(40, 41, 42)
        }
      }
      // Sanity check before running
      const result = structuredClone(Expected.before)
      assert.deepEqual(result.physicsSystem, Expected.before.physicsSystem)
      assert.deepEqual(result.physicsPreTransformSystem, Expected.before.physicsPreTransformSystem)
      assert.deepEqual(result.transformSystem, Expected.before.transformSystem)
      // Run and Check the results
      Physics.applyImpulse(physicsWorld, testEntity, testImpulse)
      // .. Phase 1
      execute.physicsSystem()
      result.physicsSystem = getComponent(testEntity, TransformComponent).position.clone()
      assert.deepEqual(result.physicsSystem, Expected.after.physicsSystem)
      assert.deepEqual(result.physicsPreTransformSystem, Expected.before.physicsPreTransformSystem)
      assert.deepEqual(result.transformSystem, Expected.before.transformSystem)
      // .. Phase 2
      execute.physicsPreTransformSystem()
      result.physicsPreTransformSystem = getComponent(testEntity, TransformComponent).position.clone()
      assert.deepEqual(result.physicsSystem, Expected.after.physicsSystem)
      assert.deepEqual(result.physicsPreTransformSystem, Expected.after.physicsPreTransformSystem)
      assert.deepEqual(result.transformSystem, Expected.before.transformSystem)
      // .. Phase 3
      execute.transformSystem()
      result.transformSystem = getComponent(testEntity, TransformComponent).position.clone()
      assert.deepEqual(result.physicsSystem, Expected.after.physicsSystem)
      assert.deepEqual(result.physicsPreTransformSystem, Expected.after.physicsPreTransformSystem)
      assert.deepEqual(result.transformSystem, Expected.after.transformSystem)
    })
  }) //:: Category 1
}) //:: Integration : PhysicsSystem + PhysicsPreTransformSystem + TransformSystem
