# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as root-builder

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install build-essential meson python3-testresources python3-venv python3-pip git
RUN npm install -g lerna cross-env rimraf ts-eager --loglevel notice

