# syntax = docker/dockerfile:1.2
# not slim because we need github depedencies
FROM node:16-buster-slim as root-builder

RUN apt update
# Create app directory
WORKDIR /app

RUN apt-get -y install build-essential meson python3-testresources python3-venv python3-pip git

COPY package.json .
COPY packages/common/package.json ./packages/common/
COPY packages/engine/package.json ./packages/engine/
COPY packages/hyperflux/package.json ./packages/hyperflux/
COPY packages/matchmaking/package.json ./packages/matchmaking/
COPY packages/projects/package.json ./packages/projects/
COPY packages/server-core/package.json ./packages/server-core/
COPY project-package-jsons ./

ARG NODE_ENV
RUN npm install --loglevel notice --legacy-peer-deps