export * from "./classes";
export * from "./components";
export * from "./defaults";
export * from "./interfaces";
export * from "./systems";
export * from "./types";
import { Entity, World } from "ecsy";
import InputActionHandler from "./components/InputActionHandler";
import InputAxisHandler2D from "./components/InputAxisHandler2D";
import InputReceiver from "./components/InputReceiver";
import InputActionTable from "./interfaces/InputActionTable";
export { InputReceiver, InputActionHandler, InputAxisHandler2D };
export declare function initializeInputSystems(world: World, options?: {
    mouse: boolean;
    keyboard: boolean;
    touchscreen: boolean;
    gamepad: boolean;
    debug: boolean;
}, inputMap?: InputActionTable): World | null;
export declare function addInputHandlingToEntity(entity: Entity, inputFilter?: InputActionTable): Entity;
