import { Component } from "@xr3ngine/engine/src/ecs/classes/Component";
export declare class Avatar extends Component<any> {
    model: any;
    options: {};
    skinnedMeshes: any[];
    flipZ: boolean;
    flipY: boolean;
    flipLeg: boolean;
    allHairBones: any[];
    hairBones: any[];
    fingerBones: any;
    tailBones: any;
    armature: any;
    skeleton: any;
    Eye_L: any;
    Eye_R: any;
    Head: any;
    Neck: any;
    Chest: any;
    Hips: any;
    Spine: any;
    Left_shoulder: any;
    Left_wrist: any;
    Left_elbow: any;
    Left_arm: any;
    Right_shoulder: any;
    Right_wrist: any;
    Right_elbow: any;
    Right_arm: any;
    Left_ankle: any;
    Left_knee: any;
    Left_leg: any;
    Right_ankle: any;
    Right_knee: any;
    Right_leg: any;
    modelBones: {
        Hips: any;
        Spine: any;
        Chest: any;
        Neck: any;
        Head: any;
        Left_shoulder: any;
        Left_arm: any;
        Left_elbow: any;
        Left_wrist: any;
        Left_leg: any;
        Left_knee: any;
        Left_ankle: any;
        Right_shoulder: any;
        Right_arm: any;
        Right_elbow: any;
        Right_wrist: any;
        Right_leg: any;
        Right_knee: any;
        Right_ankle: any;
    };
    poseManager: any;
    shoulderTransforms: any;
    legsManager: any;
    inputs: any;
    height: any;
    shoulderWidth: any;
    leftArmLength: any;
    rightArmLength: any;
    lastModelScaleFactor: number;
    lastTimestamp: number;
    decapitated: boolean;
    modelBoneOutputs: any;
    volume: number;
    outputs: any;
    constructor({ object, options }: {
        object: any;
        options?: {};
    });
    initializeBonePositions(setups: any): void;
    update(): void;
    decapitate(): void;
    undecapitate(): void;
    destroy(): void;
}
export default Avatar;
