ARG ECR_URL
ARG REPO_NAME
ARG STAGE
FROM ${ECR_URL}/${REPO_NAME}-root:latest_${STAGE} as builder

# Create app directory
WORKDIR /app

# to make use of caching, copy only package files and install dependencies
COPY packages/taskserver/package.json ./packages/taskserver/

ARG NODE_ENV
RUN npm install --loglevel notice --production

COPY . .

# copy then compile the code

ENV APP_ENV=production

FROM node:18-buster-slim as runner
WORKDIR /app

COPY --from=builder /app ./

CMD ["scripts/start-server.sh"]
