sonar.projectKey=ir-engine_hyperflux
sonar.organization=ir-engine
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.language=js
sonar.typescript.tsconfigPaths=./



# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=ir-engine
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=./src
sonar.exclusions=**/*.json, **/*.md, **/*.test.ts, **/*.test.tsx
sonar.test.inclusions=**/*.test.ts, **/*.test.tsx

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
