import Editor from "./Editor";

import SceneNode from "@xr3ngine/engine/src/editor/nodes/SceneNode";
import SceneNodeEditor from "./properties/SceneNodeEditor";
import GroupNode from "@xr3ngine/engine/src/editor/nodes/GroupNode";
import GroupNodeEditor from "./properties/GroupNodeEditor";
import ModelNode from "@xr3ngine/engine/src/editor/nodes/ModelNode";
import ModelNodeEditor from "./properties/ModelNodeEditor";
import GroundPlaneNode from "@xr3ngine/engine/src/editor/nodes/GroundPlaneNode";
import GroundPlaneNodeEditor from "./properties/GroundPlaneNodeEditor";
import BoxColliderNode from "@xr3ngine/engine/src/editor/nodes/BoxColliderNode";
import BoxColliderNodeEditor from "./properties/BoxColliderNodeEditor";
import AmbientLightNode from "@xr3ngine/engine/src/editor/nodes/AmbientLightNode";
import AmbientLightNodeEditor from "./properties/AmbientLightNodeEditor";
import DirectionalLightNode from "@xr3ngine/engine/src/editor/nodes/DirectionalLightNode";
import DirectionalLightNodeEditor from "./properties/DirectionalLightNodeEditor";
import SpotLightNode from "@xr3ngine/engine/src/editor/nodes/SpotLightNode";
import SpotLightNodeEditor from "./properties/SpotLightNodeEditor";
import PointLightNode from "@xr3ngine/engine/src/editor/nodes/PointLightNode";
import PointLightNodeEditor from "./properties/PointLightNodeEditor";
import HemisphereLightNode from "@xr3ngine/engine/src/editor/nodes/HemisphereLightNode";
import HemisphereLightNodeEditor from "./properties/HemisphereLightNodeEditor";
import SpawnPointNode from "@xr3ngine/engine/src/editor/nodes/SpawnPointNode";
import SpawnPointNodeEditor from "./properties/SpawnPointNodeEditor";
import WayPointNode from "@xr3ngine/engine/src/editor/nodes/WayPointNode";
import WayPointNodeEditor from "./properties/WayPointNodeEditor";
import SkyboxNode from "@xr3ngine/engine/src/editor/nodes/SkyboxNode";
import SkyboxNodeEditor from "./properties/SkyboxNodeEditor";
import FloorPlanNode from "@xr3ngine/engine/src/editor/nodes/FloorPlanNode";
import FloorPlanNodeEditor from "./properties/FloorPlanNodeEditor";
import ImageNode from "@xr3ngine/engine/src/editor/nodes/ImageNode";
import ImageNodeEditor from "./properties/ImageNodeEditor";
import VideoNode from "@xr3ngine/engine/src/editor/nodes/VideoNode";
import VideoNodeEditor from "./properties/VideoNodeEditor";
import SpawnerNode from "@xr3ngine/engine/src/editor/nodes/SpawnerNode";
import SpawnerNodeEditor from "./properties/SpawnerNodeEditor";
import TriggerVolumeNode from "@xr3ngine/engine/src/editor/nodes/TriggerVolumeNode";
import TriggerVolumeNodeEditor from "./properties/TriggerVolumeNodeEditor";
import LinkNode from "@xr3ngine/engine/src/editor/nodes/LinkNode";
import LinkNodeEditor from "./properties/LinkNodeEditor";
import ParticleEmitterNode from "@xr3ngine/engine/src/editor/nodes/ParticleEmitterNode";
import ParticleEmitterNodeEditor from "./properties/ParticleEmitterNodeEditor";
import KitPieceNode from "@xr3ngine/engine/src/editor/nodes/KitPieceNode";
import KitPieceNodeEditor from "./properties/KitPieceNodeEditor";
import SimpleWaterNode from "@xr3ngine/engine/src/editor/nodes/SimpleWaterNode";
import SimpleWaterNodeEditor from "./properties/SimpleWaterNodeEditor";
import AudioNode from "@xr3ngine/engine/src/editor/nodes/AudioNode";
import AudioNodeEditor from "./properties/AudioNodeEditor";
import ScenePreviewCameraNode from "@xr3ngine/engine/src/editor/nodes/ScenePreviewCameraNode";
import ScenePreviewCameraNodeEditor from "./properties/ScenePreviewCameraNodeEditor";

import SketchfabSource from "./assets/sources/SketchfabSource";
import PolySource from "./assets/sources/PolySource";
import BingImagesSource from "./assets/sources/BingImagesSource";
import BingVideosSource from "./assets/sources/BingVideosSource";
import TenorSource from "./assets/sources/TenorSource";
import ElementsSource from "./assets/sources/ElementsSource";
import MyAssetsSource from "./assets/sources/MyAssetsSource";
import ArchitectureKitSource from "./assets/sources/ArchitectureKitSource";
import RockKitSource from "./assets/sources/RockKitSource";
import HubsSoundPackSource from "./assets/sources/HubsSoundPackSource";

export function createEditor(api, settings) {
  const editor = new Editor(api, settings);

  editor.registerNode(SceneNode, SceneNodeEditor);
  editor.registerNode(GroupNode, GroupNodeEditor);
  editor.registerNode(ModelNode, ModelNodeEditor);
  editor.registerNode(GroundPlaneNode, GroundPlaneNodeEditor);
  editor.registerNode(BoxColliderNode, BoxColliderNodeEditor);
  editor.registerNode(AmbientLightNode, AmbientLightNodeEditor);
  editor.registerNode(DirectionalLightNode, DirectionalLightNodeEditor);
  editor.registerNode(HemisphereLightNode, HemisphereLightNodeEditor);
  editor.registerNode(SpotLightNode, SpotLightNodeEditor);
  editor.registerNode(PointLightNode, PointLightNodeEditor);
  editor.registerNode(SpawnPointNode, SpawnPointNodeEditor);
  editor.registerNode(WayPointNode, WayPointNodeEditor);
  editor.registerNode(SkyboxNode, SkyboxNodeEditor);
  editor.registerNode(FloorPlanNode, FloorPlanNodeEditor);
  editor.registerNode(ImageNode, ImageNodeEditor);
  editor.registerNode(VideoNode, VideoNodeEditor);
  editor.registerNode(AudioNode, AudioNodeEditor);
  editor.registerNode(SpawnerNode, SpawnerNodeEditor);
  editor.registerNode(TriggerVolumeNode, TriggerVolumeNodeEditor);
  editor.registerNode(LinkNode, LinkNodeEditor);
  editor.registerNode(ParticleEmitterNode, ParticleEmitterNodeEditor);
  editor.registerNode(KitPieceNode, KitPieceNodeEditor);
  editor.registerNode(SimpleWaterNode, SimpleWaterNodeEditor);
  editor.registerNode(ScenePreviewCameraNode, ScenePreviewCameraNodeEditor);

  editor.registerSource(new ElementsSource(editor));
  editor.registerSource(new MyAssetsSource(editor));
  editor.registerSource(new ArchitectureKitSource(api));
  editor.registerSource(new RockKitSource(api));
  editor.registerSource(new SketchfabSource(api));
  editor.registerSource(new PolySource(api));
  editor.registerSource(new BingImagesSource(api));
  editor.registerSource(new BingVideosSource(api));
  editor.registerSource(new HubsSoundPackSource(editor));
  editor.registerSource(new TenorSource(api));

  return editor;
}
