/// <reference types="node" />
import { IBufferGeometryCompressedTexture, WorkerInitializationResponse } from "./Interfaces";
import { Scene, BufferGeometry, CompressedTexture, MeshBasicMaterial, Mesh } from "three";
export default class DracosisPlayer {
    frameRate: number;
    speed: number;
    scene: Scene;
    mesh: Mesh;
    material: MeshBasicMaterial;
    bufferGeometry: BufferGeometry;
    compressedTexture: CompressedTexture;
    private _startFrame;
    private _endFrame;
    private _numberOfFrames;
    private _currentFrame;
    private _loop;
    private _playOnStart;
    private _isinitialized;
    private _onLoaded;
    private _ringBuffer;
    private _dataBufferSize;
    private _filePath;
    private _isPlaying;
    private _fileHeader;
    private _fileReadStream;
    private _readStreamOffset;
    private _decoderModule;
    private _encoderModule;
    private _basisTextureLoader;
    private _nullBufferGeometry;
    private _nullCompressedTexture;
    private _pos;
    private _frameNumber;
    private _framesUpdated;
    private _numberOfBuffersRemoved;
    get currentFrame(): number;
    get startFrame(): number;
    set startFrame(value: number);
    get endFrame(): number;
    set endFrame(value: number);
    get loop(): boolean;
    set loop(value: boolean);
    httpGetAsync(theUrl: any, callback: any): void;
    constructor(scene: any, filePath: string, onLoaded: any, playOnStart?: boolean, loop?: boolean, startFrame?: number, endFrame?: number, speedMultiplier?: number, bufferSize?: number);
    handleMessage(data: any): void;
    handleInitializationResponse(data: WorkerInitializationResponse): void;
    handleDataResponse(data: IBufferGeometryCompressedTexture[]): void;
    getPositionInBuffer(frameNumber: number): number;
    handleBuffers(): NodeJS.Timeout;
    update(): NodeJS.Timeout;
    play(): void;
    pause(): void;
    reset(): void;
    goToFrame(frame: number, play: boolean): void;
    setSpeed(multiplyScalar: number): void;
    show(): void;
    hide(): void;
    fadeIn(stepLength: number, fadeTime: number, currentTime?: number): void;
    fadeOut(stepLength: number, fadeTime: number, currentTime?: number): void;
}
